### ISSUE TITLE
Progress Bar fill doesn't have rounded corners

### ISSUE THREAD

**Issue by flutefreak7** [ColinDuquesnoy/QDarkStyleSheet#101]
As seen in the current example here: https://raw.githubusercontent.com/ColinDuquesnoy/QDarkStyleSheet/master/screenshots/qdarkstyle_containers_tabs_displays.png

The progress bar "fill" is a simple rectangle with no corner rounding causing its corners to overlap the corner rounding of the empty progressbar widget.

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting the issue. I and @dpizetta are very busy with personal stuffs at the moment so it may take a bit of time before this issue get fixed. Feel free to submit a PR if you find a fix :wink:

**Comment by dpizetta** [comment]
It should be solved  with the new style :)
