### ISSUE TITLE
QMenu indicator on QPushButton is cropped

### ISSUE THREAD

**Issue by gusmd** [ColinDuquesnoy/QDarkStyleSheet#102]
# Environment:

- QDarkStyle: Latest master (cc761f7)
- OS: Windows 10
- Qt 5.11.1
- MSVC 2017 (C++)

# Issue

When setting a `QMenu` in a `QPushButton` using `QPushButton::setMenu(QMenu *menu)`, the down-arrow indicator is not well positioned and is cropped by the button boundaries. See picture below for QDarkStyleSheet vs. default Windows 10 style.

![qdarkstylesheet_menu](https://user-images.githubusercontent.com/7676114/43410768-e20e85e8-93dc-11e8-969e-a325b9af4a2d.PNG) vs. ![default_menu](https://user-images.githubusercontent.com/7676114/43410949-7f9e6b5c-93dd-11e8-9263-e5ac1270a73a.PNG)

The menu can be added with code like this:
```cpp
QMenu *menu = new QMenu(this);
menu->addAction("Noop");
ui->myButton->setMenu(menu);
```

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting the issue. I and @dpizetta are very busy with personal stuffs at the moment so it may take a bit of time before this issue get fixed. Feel free to submit a PR if you find a fix :wink:

**Comment by gusmd** [comment]
No problem. I appreciate the work you guys have done! I'll see if I can figure this one out :)
