### ISSUE TITLE
QLineEdit

### ISSUE THREAD

**Issue by bakerbrown** [ColinDuquesnoy/QDarkStyleSheet#103]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: Dev 
- OS: Windows 7
- Python: 3.6

[If used, please inform their versions]

- PySide2: 5.11.1
- PyQt: 5.11.2
- PyQtGraph:
- QtPy:
- QT_API:
- PYQTGRAPH_QT_LIB:

### Language

Python

### Actual Result

When using a standard Qt designer QLineEdit from the palette. See picture below for QDarkStyleSheet vs. default Windows 7 style.

![screen](https://user-images.githubusercontent.com/15327041/43724434-dab812c2-9991-11e8-885b-d54c1cdff1f4.png)
![screen2](https://user-images.githubusercontent.com/15327041/43724440-de66288c-9991-11e8-815c-b073f217cfa5.png)

**Comment by flutefreak7** [comment]
Huh, I had this same issue and I worked around it by adding 2 pixels to all my QLineEdit heights since that's the amount the boxes are corner rounded with this theme.  You'd think the corner round wouldn't cause clipping, though, so I hope this gets resolved.

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting the issue. I and @dpizetta are very busy with personal stuffs at the moment so it may take a bit of time before this issue get fixed. Feel free to submit a PR if you find a fix :wink:

**Comment by dpizetta** [comment]
I think now it is resolved. Any problem, please reopen this issue. Tks for reporting.
