### ISSUE TITLE
Text cut off (looks like margins?) when push button is disabled

### ISSUE THREAD

**Issue by RustyPedrosa** [ColinDuquesnoy/QDarkStyleSheet#106]
Hi guys,

I'm new to Qt and python, so please accept my apologies if this is a mistake on my end.  I love the work you've done with this stylesheet, but I'm seeing this minor issue.

### Describe Your Environment
Tried in two environments:
- QDarkStyle: 2.5.4
- OS: WIndows 10
- Python: 3.6.6
- PyQt: 5.11.2

Also tried with Ubuntu 18.04 on Windows Subsystem for Linux running Xming 6.9.0.31
- QDarkStyle: 2.5.4
- OS: Ubuntu 18.04 (WSL)
- Python: 3.6.5
- PyQt: 5.11.2

### Language
- [Python]

### Description / Steps to Reproduce [if necessary]
When I disable a pushbutton on my UI, as in:
`self.ui.pushButton_readData.setEnabled(False)`
the text on the button is cut off if it's too close to the sides.

### Actual/Expected Result
Screenshot from Windows: [Imgur](https://i.imgur.com/OOZ6Bo7.png)

It's hard to see, but "Read Data" is cut off on the sides (the 'R' and 'a' are almost gone) with qdarkstylesheet (left).

It looks fine without the stylesheet applied (right).

In Linux it's almost exactly the same.. maybe one more pixel is cut off.

Thanks!  Keep up the good work!

**Comment by dpizetta** [comment]
Hi, it looks like that margin or padding is different when the button is up and down. Are you able to try to fix it and make a PR? Both of us are busy :)

**Comment by dpizetta** [comment]
I think now it is resolved. Tks for reporting. I could not reproduce your issue in the example, even changing the size. If not revolved with the new version, please reopen this issue.
