### ISSUE TITLE
Text cut off and background color not full width when using comboboxes with a BG color

### ISSUE THREAD

**Issue by CAM-Gerlach** [ColinDuquesnoy/QDarkStyleSheet#111]
### Describe Your Environment

- QDarkStyle: 2.5.4
- OS: Windows 8.1 x64
- Python: 3.6.6 x64

- PyQt: 5.9.2
- Qt: 5.9.6
- QtPy: 1.4.2
- QT_API: ?

### Language

Python (Anaconda)

### Description / Steps to Reproduce

We are in the process of implementing a dark theme using ``QDarkStyle`` in the Spyder IDE as tracked by spyder-ide/spyder#8068 , and in the course of reviewing the initial implement in @dalthviz 's spyder-ide/spyder#8020 , I noticed a number of issues that Spyder maintainer @ccordoba12 identified as being within the scope of this upstream rather than our specific usage, among them this one, and requested I open this here.

Specifically, comboboxes with a background color, dynamic or static, only display it over a small fraction of the box size (i.e. with a large border), rather than all the way to the edges of the box. Further, this restricts text to this small region, thus cutting it off.

To reproduce:

1. Create a combobox with a background
2. Enter text in combobox
3. Observe that the text is partially cut off

As an unrelated note, you have a few minor bugs in your github template: Your comments are using ``[]`` instead of ``<!--- -->`` as is the correct GFM (really, HTML) comment syntax, and there's a strange typo ``output ou image`` [???] in some of the image-related comments

### Actual Result

As implemented in Spyder via its new dark theme, the comboboxes with a background color have the text cut off. For example, this is the find widget without the dark theme:

![image](https://user-images.githubusercontent.com/17051931/46910423-6fac0580-cf09-11e8-8714-0209f901a32d.png)

![image](https://user-images.githubusercontent.com/17051931/46910427-86525c80-cf09-11e8-9cda-4719d145d76c.png)

And with the dark theme:

![image](https://user-images.githubusercontent.com/17051931/46910442-e943f380-cf09-11e8-9017-e77cd101341e.png)

![image](https://user-images.githubusercontent.com/17051931/46910439-d7625080-cf09-11e8-8140-37ab3185deb0.png)

### Expected Results / Proposed Result

The color background and the text should extend to the full border of the combobox, as occurs without a background.

### Relevant Code

See spyder-ide/spyder#8020

**Comment by dpizetta** [comment]
Taking care of this also this week! Tks

**Comment by dpizetta** [comment]
This seems to be something in Windows. I need to check because I cannot reproduce it on Linux. Take a look. And the #103 it is also Windows. 

Could you check something for me? Run the example from QDarkStyle on windows and send me the screenshot. By now I do not have windows. Tks

![screenshot linux 2018-10-25 01 26 23](https://user-images.githubusercontent.com/5084939/47476239-d5479e00-d7f5-11e8-8ea8-9e5719f40202.png)
![screenshot linux 2018-10-25 01 15 53](https://user-images.githubusercontent.com/5084939/47476242-d8428e80-d7f5-11e8-80a4-cf469739f6a7.png)
![screenshot linux 2018-10-25 01 16 06](https://user-images.githubusercontent.com/5084939/47476251-e55f7d80-d7f5-11e8-8199-7b958e340e40.png)

**Comment by dpizetta** [comment]
It may relate to #106 too.

**Comment by dpizetta** [comment]
My friend tested on windows, with the new version we cannot reproduce the problem.  

![xtela02](https://user-images.githubusercontent.com/5084939/47526811-43807500-d877-11e8-921b-1e70f64836ee.png)

Reduced size


![xtela05](https://user-images.githubusercontent.com/5084939/47526815-454a3880-d877-11e8-9cba-26cbd793b30d.png)

**Comment by CAM-Gerlach** [comment]
@dpizetta Sorry for the delay; I was busy with another project and then my friend's apartment got burned to the ground.

Here's the example checked out on Windows 8.1 x64 and Python 3.6.6 running in the same Anaconda environment as Spyder, with the 2.5.4 release commit (the version used previously with Spyder):

![image](https://user-images.githubusercontent.com/17051931/47535161-f785fe00-d87f-11e8-96b5-e93008e51535.png)

and with the latest ``master`` commit:

![image](https://user-images.githubusercontent.com/17051931/47535255-374ce580-d880-11e8-9f0d-cb6c5621c28b.png)

I didn't see any specific instructions, but I also edited ``qdarkstyle/style.qss`` to add the ``background-color`` as above, but it didn't actually have any effect either way—I assume I'm just missing something obvious, since as mentioned I'm not the Qt/GUI guy on the team and am a total n00b at any of this stuff.

I also uninstalled the stable build of QDarkStyle, installed the latest development master (with ``pip install -e .``) and run Spyder again in that environment, and while everything worked the combobox situation was exactly the same as before, with regard to any that had a background.

Let me know what/how you'd like me to test further. Thanks!

**Comment by dpizetta** [comment]
It seems to be solved!!!! :) I was the problem with padding of LineEdit, in other applications (only not our test window) it seems it inherits some padding in the lineEdit. I've tested on Spyder and it worked.

![screenshot linux 2018-10-26 23 57 51](https://user-images.githubusercontent.com/5084939/47598996-61cf9900-d97b-11e8-8dc4-61959c856b21.png)

**Comment by CAM-Gerlach** [comment]
Great! Thanks so much @dpizetta !
