### ISSUE TITLE
Extremely difficult to read "disabled"/"grayed-out" text and embedded hyperlinks due to low contrast

### ISSUE THREAD

**Issue by CAM-Gerlach** [ColinDuquesnoy/QDarkStyleSheet#112]
### Describe Your Environment

- QDarkStyle: 2.5.4
- OS: Windows 8.1 x64
- Python: 3.6.6 x64

- PyQt: 5.9.2
- Qt: 5.9.6
- QtPy: 1.4.2
- QT_API: ?

### Language

Python (Anaconda)

### Description / Steps to Reproduce

We are in the process of implementing a dark theme using ``QDarkStyle`` in the Spyder IDE as tracked by spyder-ide/spyder#8068 , and in the course of reviewing the initial implement in @dalthviz 's spyder-ide/spyder#8020 , I noticed a number of issues that Spyder maintainer @ccordoba12 identified as being within the scope of this upstream rather than our specific usage, among them this one, and requested I open this here.

1. Make some text disabled (i.e. a disabled menu option, checkbox, etc) or a hyperlink
2. Try (and fail) to read it

### Actual Result

Disabled text completely illegible, even by a user with typical vision and a properly calibrated Pro-IPS monitor. 

![image](https://user-images.githubusercontent.com/17051931/46910654-a71cb100-cf0d-11e8-836e-453bbcb10d8c.png)

Hyperlinks are also almost as hard to read on a dark background:

![image](https://user-images.githubusercontent.com/17051931/46910668-c6b3d980-cf0d-11e8-8795-ba62a3641786.png)

### Expected Results / Proposed Result

Disabled text should be lighter, to improve contrast and thus legibility, so users can clearly see what they are missing. Similarly, hyperlinks should use one of the lighter blues in your palette to make them more readable.

### Relevant Code

See spyder-ide/spyder#8020

**Comment by dpizetta** [comment]
Hi, I will take care of this. I am preparing a more simple and better palette. I hope this week I would finish!

**Comment by CAM-Gerlach** [comment]
@dpizetta Fantastic, thanks so much!

**Comment by dpizetta** [comment]
I think I cannot fix the hyperlinks. As they use RichText it seems that the application CSS does not have access to it. If you check the text created with rich text it already has "a {color:blue;}; inside. 

- https://bugreports.qt.io/browse/QTBUG-34114
- https://stackoverflow.com/questions/13416183/qt-stylesheet-how-to-set-color-of-qpalettelink-and-qplattelinkvisited
- https://stackoverflow.com/questions/5497799/how-do-i-customise-the-appearance-of-links-in-qlabels-using-style-sheets

Some references below. I think you can choose a median color that works for both, white and black themes I suggested this one: #4D545B, I am using now for text disabled - see pictures below. That original blue is also ugly for white theme :).

![screenshot linux 2018-10-25 00 43 58](https://user-images.githubusercontent.com/5084939/47475040-4a17d980-d7f0-11e8-8e33-441bc31dc027.png)
![screenshot linux 2018-10-25 00 49 03](https://user-images.githubusercontent.com/5084939/47475045-4c7a3380-d7f0-11e8-9228-76876240f7d1.png)
![screenshot linux 2018-10-25 00 49 12](https://user-images.githubusercontent.com/5084939/47475049-4edc8d80-d7f0-11e8-8736-f689a1ab527c.png)

The issue about the disabled text was corrected, I think. :)

![screenshot linux 2018-10-25 00 52 55](https://user-images.githubusercontent.com/5084939/47475164-babef600-d7f0-11e8-838a-2b372daff309.png)

I will upload soon, making some more tests here.

**Comment by flutefreak7** [comment]
I was doing workarounds to deal with the disabled text, so I'm very grateful for this fix as well!

**Comment by CAM-Gerlach** [comment]
Thanks @dpizetta , sounds good! @dalthviz take note.

**Comment by dpizetta** [comment]
Closing for now :)

**Comment by CAM-Gerlach** [comment]
Thanks @dpizetta !

**Comment by ccordoba12** [comment]
@dpizetta, when do you plan to release a new version of QDarkStyle? I say it because we'd like to use it along with our next Spyder 4 beta.

**Comment by dpizetta** [comment]
Hi @ccordoba12 , @CAM-Gerlach , the new release is planned to be tomorrow. This new style has improved some spacing in Spyder also. I think the most annoying issue is that the buttons on tabs - superior part, they use tool buttons, that seems strange. I will try to improve the tool button in the next release, I've already tried by it is not so easy as I thought. There is a new icon package for the dark theme in v4?
