### ISSUE TITLE
Missing style for QTabWidget's scroll buttons

### ISSUE THREAD

**Issue by sindney** [ColinDuquesnoy/QDarkStyleSheet#115]
![qtabwidget](https://user-images.githubusercontent.com/1331120/47769455-f25cff00-dd16-11e8-8972-e280ff7e83c8.png)
```c
qTabWidget->setUsesScrollButtons(true);
```
to enable scroll bar when there's many tabs.
http://doc.qt.io/qt-5/qtabwidget.html#usesScrollButtons-prop

**Comment by dpizetta** [comment]
Hi, @sindney what is the version of qdarkstyle you are using? Did this happen in the previous versions?

Tks

**Comment by sindney** [comment]
![spliter](https://user-images.githubusercontent.com/1331120/47826971-22a7aa80-ddb6-11e8-9b30-16447382a769.png)
Right, it's fixed in the newest version, but i found that the new spliter widget seems incorrect.
it's like been focused when there's no focus at all, i guess it's flipped with it's normal state?

**Comment by sindney** [comment]
Line 1756 of style.qss
the default handle border color is lightblue 
```css
QSplitter::handle {
    border: 1px solid #179AE0;
}
```
is this a mistake or it's just designed to color like that?

**Comment by dpizetta** [comment]
Although its blue (from the older version), the sizes restrictions should not permit to show the border.  You can see in the up to date [screenshot](https://github.com/ColinDuquesnoy/QDarkStyleSheet). When you hover the splitter it should just brighten the grey color. I will improve this part of the code soon. Tks

**Comment by flutefreak7** [comment]
Yeah in most places I use dock widgets, but in a few places I use a
splitter and the blue style on the splitter is very bright (maybe
distracting?) compared to the subtle gray grip between dockwidgets.

I'm fine with the style/color being whatever the community wants because
everyone has different styles, but I'd argue that it must be consistent
across similar widgets.

Sounds like you're on it, which is good to hear!

**Comment by dpizetta** [comment]
Since there is no splitter in our example, not a manually one, just separators I've unnoticed. I've just released a new version. Can you check it? I think it is solved, it should be equal to the windows splitter, if any problems, reopen here. Tks

**Comment by sindney** [comment]
Tested, fix confirmed, thanks.
