### ISSUE TITLE
Tabs have low contrast with each other and their associated pane, and the close button is much too small

### ISSUE THREAD

**Issue by CAM-Gerlach** [ColinDuquesnoy/QDarkStyleSheet#118]
### Describe Your Environment

- QDarkStyle: 2.6.1 (``pip``)
- OS: Win 8.1 x64
- Python: 3.6.6

- PyQt: 5.9.2
- QtPy: 1.5.1
- Qt: 5.9.6

### Language

Python

### Description / Steps to Reproduce [if necessary]

These issues are with regard to QDarkStyle as used in the development versions of Spyder 4; I was assured by @ccordoba12 that these issues are due to QDarkStyle rather than something in Spyder. Three related issues:

* The tab close button for the various tabs that have it (e.g. in the Editor and the IPython console) is far too small, illegible, difficult to click (the hitbox is larger than the button, but not by much) and almost impossible to tell its been moused over:

  Normal theme:

  ![image](https://user-images.githubusercontent.com/17051931/48170385-f6f85900-e2bc-11e8-9903-f6ab70247e59.png)

  Not active tab:

  ![image](https://user-images.githubusercontent.com/17051931/48170440-2d35d880-e2bd-11e8-9701-079d56dfde05.png)

  Active tab:

  ![image](https://user-images.githubusercontent.com/17051931/48170459-39219a80-e2bd-11e8-8224-03807086197a.png)

  Active and moused over:

  ![image](https://user-images.githubusercontent.com/17051931/48170516-8140bd00-e2bd-11e8-803d-08232a6383de.png)

* Aside from the active tab, it is almost impossible to see the borders of tabs, both in the Editor/IPython console, and in the pane tabs:

  Normal theme:

  ![image](https://user-images.githubusercontent.com/17051931/48170544-a59c9980-e2bd-11e8-9b86-deb9d2501a5a.png)

  vs. dark theme

  ![image](https://user-images.githubusercontent.com/17051931/48170591-d7adfb80-e2bd-11e8-99eb-4b524842887d.png)

  and

  ![image](https://user-images.githubusercontent.com/17051931/48170689-2196e180-e2be-11e8-8338-1b7188f5e0aa.png)

  vs.

  ![image](https://user-images.githubusercontent.com/17051931/48170660-0fb53e80-e2be-11e8-9a7e-3d9b8ee3d078.png)

* The tabs, especially the pane tabs are very hard to tell apart from the panes themselves, and its hard to tell what tabs belong to what pane (upper or lower).

Thanks, and let me know if you need more information or help testing a fix!

**Comment by CAM-Gerlach** [comment]
Part of #8068 . Thanks so much for your help so far; Spyder's looking much better already because of it!

**Comment by CAM-Gerlach** [comment]
That's amazing! What do you do with NASA? At what Center? Oh and most importantly...will Pegasus/ICON ever launch hehe? 

That's so cool, so many connections! Our department's actually based at the NSSTC on campus, which is a NASA facility and most of my colleges work there on NASA GRAs (the grants I have right now were pulled from a separate pool of NASA-NOAA money for GOES-R, although I'm going to apply for the NASA NESSF this year). We have a lot of aerospace double-majors in our program and in the AMS. and in fact one of my friends just completed work on a new severe convective wind nowcasting system for NASA launches at the Cape (in fact, I first met him before I decided on UAH and hearing of an opportunity like that was the decisive factor that got me hooked on UAH).

What's more, my roommate's an aerospace Ph.D at UAH who wants to work for NASA, both my grandfathers worked for NASA though I never really knew them while they were alive (one was an electrical engineer who developed the medical recording system for Gemini and later SOSUS for the Navy, and the other was a patent attorney during Apollo the Apollo through early STS era) and NASA's certainly one of my top choices for employment once I get my Ph.D. If I hadn't been so into meteorology from before I could talk I'd have probably done aerospace or something similar, since I've always loved space more than anything. I can't wait to get down to the Cape again for another launch after seeing the last one (FH demo flight, and from a boat just offshore of the landing pads to watch the boosters fly right over our heads and land a few km away).

But I digress, hehe!

**Comment by flutefreak7** [comment]
So awesome! I'm still in Huntsville at MSFC. I run across NSSTC folks in training classes sometimes. I do solid propulsion performance analysis. Part of my job is supporting Launch Services Program, so I know several folks who were on console for the ICON cancellation and missed some meetings today because of the late night.

You PhD types have a touch of crazy! I was definitely ready to start working and getting paid once I had my bachelor's, though I did enjoy school more than most. I've topped with getting a master's - I was I'm Purdue distance learning paid for by NASA, but then we had a kid and I have no time.

We definitely should connect outside of this GitHub Issue!

**Comment by dpizetta** [comment]
The version 2.6.2, not released in PyPI yet should address this issue. Can you check? Tks

**Comment by dpizetta** [comment]
![screenshot linux 2018-11-08 15 22 17](https://user-images.githubusercontent.com/5084939/48221511-751a3580-e379-11e8-81d8-a155a00ded29.png)

**Comment by CAM-Gerlach** [comment]
@dpizetta Thanks! That's definitely better in my testing, but perhaps not quite all the way there. The button graphic is still a tad small for me, while the actual clickable area is substantially larger; my mouse was approximately where the red arrow is drawn in the screenshot and the button is still activated. So, as there's no real benefit to having the button smaller than its "hitbox", it seems either the button should be made larger, the hitbox made smaller, or some combination of both.

![image](https://user-images.githubusercontent.com/17051931/48223900-e5b35900-e35d-11e8-88ef-49ebc81592f8.png)

Also, while the tabs are easier to see with the lighter color its still kinda tough, especially people with less than ideal vision. Do you think you could make the tab color a little lighter-er? The contrast with the active tab color would be slightly reduced, but that could be bumped up a little further or just tolerated since there's also the blue bar to indicate the active tab.

**Comment by CAM-Gerlach** [comment]
@flutefreak7 Amazing stuff! It would certainly be really cool to connect sometime, and my roommate also would be really thrilled to talk to you since that's something like what he wants to do. Don't hesitate to email me at the email on my Github profile (CAM.Gerlach@Gerlach.CAM). And next time I go down to watch an RTLS launch down at the Cape, I can definitely save you a spot on the boat (though with the number of people who've expressed interest in that to me after the spectacle of the FH launch, we might need a bigger boat).

**Comment by dpizetta** [comment]
Hi @CAM-Gerlach, tks. CAn you try this another one, it should be better. About the hitbox, I need to change the size of the icon, because I cannot control via width/height parameters for the close button. So I've put a padding. I changed to the border and reduced the size, the hitbox is small, but not the best yet. This will be done in the future. I've changed the palette, for better contrast.

![screenshot linux 2018-11-09 15 31 44](https://user-images.githubusercontent.com/5084939/48278520-e66aee80-e434-11e8-874a-2405c4ae25f9.png)

![palette](https://user-images.githubusercontent.com/5084939/48278605-2af68a00-e435-11e8-879a-8016960e88dc.png)

**Comment by dpizetta** [comment]
Tks :) Thank you for your work there!
