### ISSUE TITLE
qdarkstyle console_script failure because example dir not included on PyPI

### ISSUE THREAD

**Issue by reneeotten** [ColinDuquesnoy/QDarkStyleSheet#119]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: 2.6.1
- OS: macOS, installed through MacPorts (while attempting to upgrade the port)
- Python: 2.7, 3.7 (tested both, but issue is independent of version)

### Language

Python

### Description / Steps to Reproduce [if necessary]
Attempting to use the console_script ```qdarkstyle``` fails with an ```ImportError``` (see below):
```
Traceback (most recent call last):
  File "/opt/local/bin/qdarkstyle-2.7", line 11, in <module>
    load_entry_point('QDarkStyle==2.6.1', 'console_scripts', 'qdarkstyle')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qdarkstyle/__main__.py", line 6, in <module>
    from example import example
ImportError: No module named example
```

Problem seems to me that the ```example``` directory is not include on PyPI. Adding it to ```MANIFEST.in``` should solve this. Thank you!

**Comment by dpizetta** [comment]
> Problem seems to me that the example directory is not included on PyPI. Adding it to MANIFEST.in should solve this. Thank you!

This is the best approach, but I will change it in the version three the structure. Version 2.6.3 I've fixed. removing some unnecessary imports, but at this moment the example cannot be executed from the PyPI version. Are you planning to use the example?

**Comment by reneeotten** [comment]
I personally use it because it's a dependency of spyder, so I don't really need to use the examples. Nevertheless, ideally when you install it (either with pip, MacPorts or any aother package manager)  all pieces should work, which isn't the case right now. That's why I reported it here. I don't really see what's fixed in version 2.6.3 - if you released a new version to PyPI anyway, why not include the examples there at the same time? Thanks anyway, and I could switch for the MacPorts port to downloading from GitHub instead of PyPI.

**Comment by dpizetta** [comment]
The problem is that example folder is not a python package now. If I include in the MANIFEST it will not run and you cannot call the example itself from the command line. So I removed the example call from the __main__, then no importing error is issued. In version 3 we will try to include the example inside the package, so the command line will work fine and the files will be in the right place, but need some discussion with @ColinDuquesnoy about this inclusion. Tks :)

**Comment by ColinDuquesnoy** [comment]
I don't see why we ship examples with the main package. At the very least examples should be shipped in another optional package, e.g. ``qdarkstyle_example``. IMHO we should not ship examples at all, examples are mainly for developers or users who would like to test the style-sheet without installing...

**Comment by reneeotten** [comment]
sure, I can see your point and am fine with not shipping the example with the main package. However, in that case the main package should also not refer the them, which was happening initially and that's why I reported it here. In the latest version I checked it seems like the console_script doesn't rely on it anymore so AFAIC it's all good now. Thanks for the help and responses.
