### ISSUE TITLE
macOS: Some widgets have no frame

### ISSUE THREAD

**Issue by max3-2** [ColinDuquesnoy/QDarkStyleSheet#126]
### Describe Your Environment

[Versions from your environment]
Information about your current environment setup:
  - QDarkStyle: 2.6.5
  - OS: Darwin 18.2.0 x86_64
  - Platform: darwin
  - Python: 3.7.1.final.0
  - Python API: 1013
  - Binding in use:     Not set or nonexistent
  - Abstraction in use: Not set or nonexistent
  - qtpy (QT_API):                Not set or nonexistent
  - pyqtgraph (PYQTGRAPH_QT_LIB): Not set or nonexistent
  - Qt.py (__binding__):          Not set or nonexistent

Qt bindings available:
  - PyQt5

Qt abstraction layers available:
  - qtpy

### Language

[Python]

### Description / Steps to Reproduce [if necessary]

On macOS, QListWidget and QTableWidget and QFrame have no border

1. Build an UI with List, Frame or Table

### Actual Result

The said widgets have no border. The blue border does show on hover, see images attached. This only occurs on macOS so far, the same application runs smooth on windows.  

### Expected Results / Proposed Result

Have a faint gray border around widgets even if they are not in focus

<img width="518" alt="bildschirmfoto 2018-12-24 um 13 10 03" src="https://user-images.githubusercontent.com/10244463/50399322-eaea2d00-077e-11e9-9bf3-a83c3143bf78.png">
<img width="616" alt="bildschirmfoto 2018-12-24 um 13 10 12" src="https://user-images.githubusercontent.com/10244463/50399323-eaea2d00-077e-11e9-9a4c-41c6b4a87140.png">

**Comment by max3-2** [comment]
This might be a duplicate of #123 since all widgets are in tabs. Is the fix already in the newest release?

**Comment by dpizetta** [comment]
Hi @max3-2, yep, this is related to the #123, I'll try a better fix for this. I hope to get a solution soon.

**Comment by SomberNight** [comment]
This is not specific to Mac. I see the same on Linux and Windows too.

**Comment by max3-2** [comment]
I just checked the example where some nested widgets are present. The borders are available there so thats kind of confusing. If you need me to test something just let me know

**Comment by dpizetta** [comment]
If the problem comes back, please, reopen this issue. Tks
