### ISSUE TITLE
QCheckBox and QRadioButton resource images colour

### ISSUE THREAD

**Issue by nickdademo** [ColinDuquesnoy/QDarkStyleSheet#127]
The following resource files:
_checkbox_checked_focus.png
checkbox_indeterminate_focus.png
checkbox_unchecked_focus.png
radio_checked_focus.png
radio_unchecked_focus.png_

All have the colour: #2EC0F5
(which does not match any of the colours in the stylesheet palette).

Perhaps #148CD2 is more appropriate? Or is this colour choice intentional?

**Comment by dpizetta** [comment]
Hi, @nickdademo, I'll update the colors using the palette soon. Thanks for noticing!

**Comment by goanpeca** [comment]
@dpizetta could we better use svg files that programmatically got the right colors replaced?

**Comment by dpizetta** [comment]
Of course. 

Also, it will be nice if we can use directly .svg files, but Qt does not work well with it.

**Comment by goanpeca** [comment]
>Also, it will be nice if we can use directly .svg files, but Qt does not work well with it.

Agreed, also started working on this. I will make a separate PR

**Comment by goanpeca** [comment]
Also to generate this programmatically we would need to bring the SVGs back into de package
