### ISSUE TITLE
QTabWidget tab text label is slightly obscured during hover event

### ISSUE THREAD

**Issue by nickdademo** [ColinDuquesnoy/QDarkStyleSheet#128]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: 2.6.5
- OS: Windows 10
- Python: 3.6.5

[If used, please inform their versions]

- PyQt: 5.11.3

### Language

Python (also observed in C++).

### Description / Steps to Reproduce [if necessary]

[Description of the issue]

1. Move mouse over non-active tab page tab label

### Actual Result

As shown below, "P" is obscured:

![image](https://user-images.githubusercontent.com/1648285/50478175-bdb1af00-0a0a-11e9-8749-0205a5bcfc13.png)

### Expected Results / Proposed Result

No obscuring of text during hover event.

**Comment by dpizetta** [comment]
Closed due #130
