### ISSUE TITLE
QSS with drawControl

### ISSUE THREAD

**Issue by Khalilsqu** [ColinDuquesnoy/QDarkStyleSheet#131]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: lastes
- OS: windows 
- Python: 3.6

[If used, please inform their versions]

- PySide:
- PyQt:
- PyQtGraph:
- QtPy: yes
- QT_API:
- PYQTGRAPH_QT_LIB:

### Language

[Python] or [C++] Python

### Description / Steps to Reproduce [if necessary]

I am trying to right justify shortcuts in QMenu using this code

```
class MenuProxyStyle(QProxyStyle):
    """Menu proxy class to right justify shortcuts in QMenu"""
    def drawControl(self, element, option, painter, widget=None):
        shortcut = ""

        if element == QStyle.CE_MenuItem:
            vals = option.text.split("\t")
                
            if len(vals) == 2:
                text, shortcut = vals
                option.text = text
        super(MenuProxyStyle, self).drawControl(element, option, painter,
                                                widget)
        if shortcut:
            # Margin from the right of menu column to shortcuts.
            margin = 10
            self.proxy().drawItemText(painter,
                                      option.rect.adjusted(margin, 0, -margin,
                                                           0),
                                      Qt.AlignRight | Qt.AlignVCenter,
                                      option.palette,
                                      option.state & QStyle.State_Enabled,
                                      shortcut, QPalette.Text)
```

Then I simply use this class as to right justify shortcuts in the Menu.
```
self.file_menu = self.menuBar().addMenu(_("&File"))
self._proxy = MenuProxyStyle(self.file_menu.style())
self.file_menu.setStyle(self._proxy)
```

It works perfect when `qdarkstylesheet` is not applied, but fails otherwise, with no error reported.
`element == QStyle.CE_MenuItem:` 
`element` value never agrees with `QStyle.CE_MenuItem` value when using QDarkStyleSheet
element value is 14 when QStyle.CE_MenuItem but reported wrongly with QDSS

1. [First Step]
2. [Second Step]
3. [and so on...]

### Actual Result

[A description, output ou image of the actual result]

### Expected Results / Proposed Result

[A description, output ou image of the expected/proposed result]

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```
# code here to reproduce the problem
```

**Comment by dpizetta** [comment]
Can you have some images with and without QDSS? Tks for reporting this

**Comment by Khalilsqu** [comment]
Thanks for your response, I will update you sometime next week. Regards

**Comment by dpizetta** [comment]
Please, check if the problems persist with v2.6.8, may this was fixed #132 with #145. Tks

**Comment by dpizetta** [comment]
@Khalilsqu any update? Tks

**Comment by Khalilsqu** [comment]
sorry I got really busy with my PhD, I will update you this week. This is some miner change I am trying to implement into Spyder-IDE, it works well without dark them but fails otherwise.

**Comment by Khalilsqu** [comment]
Sorry for my late response, I by mistake deleted the branch I was working on, I am also quite busy with my PhD, 

I am trying to right justify item in all menus, Context menu and actions in Spyder-ide. I can make it works when not using dark interfaces but never managed otherwise. 

[Then I read this warning in QWidget documentation.](https://doc.qt.io/archives/qt-4.8/stylesheet.html)

**Warning: Qt style sheets are currently not supported for custom QStyle subclasses. We plan to address this in some future release.**

I thought you might have workaround!!

![white_bg](https://user-images.githubusercontent.com/22060413/59950098-e3c18480-946c-11e9-82bb-1c056ac016e5.gif)

sorry bothering you.

**Comment by Khalilsqu** [comment]
I submitted a [PR](https://github.com/spyder-ide/spyder/pull/9726) to Spyder repo.

**Comment by dpizetta** [comment]
No problems @Khalilsqu , tks for informing us!
