### ISSUE TITLE
Checkboxes appear in QComboBox drop-down list

### ISSUE THREAD

**Issue by franciszekjuras** [ColinDuquesnoy/QDarkStyleSheet#132]
- QDarkStyle: latest
- OS: Ubuntu 16.04
- Qt: 5.5.1
- C++

When using QComboBox, items on the drop-down list have checkboxes, which is different from default behaviour and causes text cutting (see attached pictures):
With QDarkStyle:
![base](https://user-images.githubusercontent.com/29258901/52710258-2f2fc780-2f8f-11e9-8d31-45e5f3dd42b6.png)
![dropdown](https://user-images.githubusercontent.com/29258901/52710257-2f2fc780-2f8f-11e9-984d-09a0db04e7b7.png)
Default:
![default](https://user-images.githubusercontent.com/29258901/52710256-2e973100-2f8f-11e9-83f9-0680fb7b69ed.png)
Is this behaviour intended? I noticed, that by deleting background-color lines in QWidget style I can get rid of checkboxes, but then obviously background colors are messed up.

**Comment by dismine** [comment]
> and causes text cutting

I confirm this.

**Comment by dpizetta** [comment]
Can you (@franciszekjuras , @dismine ) share some code so I can reproduce the problem? Also, could you run the example/example.py in the inputs tab and take a screenshot? Tks

**Comment by dpizetta** [comment]
I found other examples using Spyder v4 . Also, it appears white lines external to the combo box.

![combobox-problem](https://user-images.githubusercontent.com/5084939/56686394-42a39100-66aa-11e9-918f-9a3318d702a9.gif)
![combobox-problem-too](https://user-images.githubusercontent.com/5084939/56686399-4505eb00-66aa-11e9-9432-699f8ff7454c.gif)

Also discussed here: https://github.com/spyder-ide/spyder/issues/9199

**Comment by goanpeca** [comment]
Added a fix over https://github.com/ColinDuquesnoy/QDarkStyleSheet/pull/145
