### ISSUE TITLE
PyQtGraph plot axes / labels get covered by QDarkStyle padding

### ISSUE THREAD

**Issue by flutefreak7** [ColinDuquesnoy/QDarkStyleSheet#134]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: 2.6.5
- OS: Windows 10
- Python: 3.7.2

[If used, please inform their versions]

- PySide:
- PyQt: 5.11.3
- PyQtGraph: 0.11.0.dev0+g2e69b9c
- QtPy:
- QT_API:
- PYQTGRAPH_QT_LIB:

### Language

[Python] or [C++]

### Description / Steps to Reproduce [if necessary]

[Description of the issue]

1. Build a widget with a pyqtgraph PlotWidget
2. Apply the qdarkstyle stylesheet
3. Viewing the resulting widget shows that the axes are clipped by a dark border around the PlotWidget - this is especially noticeable when axes labels are used.

### Actual Result

A Dark 4px border obscures the axes labels:

![image](https://user-images.githubusercontent.com/2966015/53320546-97d64880-389b-11e9-8afb-0224df00f048.png)

### Expected Results / Proposed Result

With no style sheet:
![image](https://user-images.githubusercontent.com/2966015/53320592-b3d9ea00-389b-11e9-9ccb-673698ccb6e6.png)

With a PlotWidget element in the style sheet with padding = 0:
![image](https://user-images.githubusercontent.com/2966015/53320620-c522f680-389b-11e9-89cd-3f4dfffd44b4.png)

### Relevant Code [if necessary]

The code below is also available at https://gist.github.com/flutefreak7/3ffbaa0e0ad72694cd03085d0266d8fd

I create 3 widgets with the same plot:
 *  No Style Sheet
 *  Using `qdarkstyle` style sheet
 *  Using the `qdarkstyle` style sheet + a PlotWidget section with padding=0

I have also verified that the QAbstractScrollArea 4px padding is to blame.  If I remove the 4px padding line from QAbstractScrollArea, I also get the desired result.

```

from PyQt5 import QtCore, QtWidgets
import qdarkstyle

import pyqtgraph as pg

qss_plot_widget = r'''
PlotWidget {
    padding: 0px;
}
'''

app = QtWidgets.QApplication([])

class Plotter(QtWidgets.QWidget):
    def __init__(self, dark=False, fix_padding=False):
        super().__init__()

        self._layout = QtWidgets.QVBoxLayout()
        self._layout.setSpacing(0)
        self._layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self._layout)

        self._plotter = pg.PlotWidget()
        self._plotter.plot(x=[1, 2, 3, 4], y=[1, 3, 2, 4])
        self._plotter.setLabels(title='Window 1', bottom='X Axis', left='Y Axis', right='Y2 Axis')
        self._plotter.setContentsMargins(0, 0, 0, 0)

        self._layout.addWidget(self._plotter)

        if dark:

            qss = qdarkstyle.load_stylesheet_pyqt5()

            if fix_padding:
                qss += qss_plot_widget
                self.setWindowTitle('QDarkStyle + PyQtGraph Fix')
            else:
                self.setWindowTitle('QDarkStyle')

            self.setStyleSheet(qss)
        else:
            self.setWindowTitle('No Style Sheet')



plot_light = Plotter(dark=False)
plot_dark = Plotter(dark=True)
plot_dark_fixed = Plotter(dark=True, fix_padding=True)

plot_light.show()
plot_dark.show()
plot_dark_fixed.show()

plot_light.move(QtCore.QPoint(10, 100))
plot_dark.move(QtCore.QPoint(400, 100))
plot_dark_fixed.move(QtCore.QPoint(800, 100))

app.exec_()
```

**Comment by danielhrisca** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/20952040/54677772-458bee80-4b0c-11e9-8b50-0924dcb969f9.png)

![image](https://user-images.githubusercontent.com/20952040/54677857-79ffaa80-4b0c-11e9-95e1-b6336518f74b.png)

 There is also a misalignment of the color buttons

**Comment by dpizetta** [comment]
Thanks for the detailed reporting.
