### ISSUE TITLE
QTabWidget overflow scroll buttons not displaying right

### ISSUE THREAD

**Issue by EchterAgo** [ColinDuquesnoy/QDarkStyleSheet#136]
![image](https://user-images.githubusercontent.com/922233/56489483-0f2b0000-650c-11e9-9648-86e1998ba92a.png)

![image](https://user-images.githubusercontent.com/922233/56489494-1520e100-650c-11e9-9e1e-77e1247f2cc3.png)

Only the left button can be interacted with. This is how it looks without QDarkStyleSheet:

![image](https://user-images.githubusercontent.com/922233/56489555-4a2d3380-650c-11e9-918e-b05661cec73c.png)

See also https://github.com/Electron-Cash/Electron-Cash/issues/1313

**Comment by dpizetta** [comment]
Thanks for reporting!

**Comment by dpizetta** [comment]
@EchterAgo could you share some more info about your env? Just run qdarkstyle --all. Or use the [helpdev](https://pypi.org/project/helpdev/).
