### ISSUE TITLE
QLabel links not styled

### ISSUE THREAD

**Issue by goanpeca** [ColinDuquesnoy/QDarkStyleSheet#139]
<img width="1041" alt="Screen Shot 2019-04-25 at 20 02 59" src="https://user-images.githubusercontent.com/3627835/56777095-2a5c7080-6795-11e9-8764-5b2913ee3e57.png">

Not possible via QSS but this provides a fix, 

```python
app = QCoreAppilcation.instance()
palette = app.palette()
palette.setColor(QPalette.Normal, QPalette.Link, Qt.red)
app.setPalette(palette)
```

Although if we want to support hover changes, (or even visited...) we need to provide custom QLabel to handle that programmatically.

Something naive like (assumes the user has added `<a style="text-decoration:none;">...`:

```python
class QLabelLinks(QLabel):

    def __init__(self, *args, **kwargs):
        super(QLabelLinks, self).__init__( *args, **kwargs)

        self.linkHovered.connect(self._update_hover_html_link_style)

    def _update_hover_html_link_style(self, url):
        link = 'text-decoration:none;'
        link_hovered = 'text-decoration:underline;'
        self._url = url

        if url:
            QApplication.setOverrideCursor(QCursor(Qt.PointingHandCursor))
            new_text, old_text = link_hovered, link
        else:
            new_text, old_text = link, link_hovered
            QApplication.restoreOverrideCursor()

        text = self.text()
        new_text = text.replace(old_text, new_text)

        self.setText(new_text)
```

**Comment by dpizetta** [comment]
Do you mean that this class should be distributed with Qdark? What about keeping this class on the "user" app?

**Comment by goanpeca** [comment]
Hmm maybe ? Do not know or have a known issues section with tips like how to fix it. However I do think that the palette fix should be implemented. Either by running a helper function or similar.

**Comment by dpizetta** [comment]
We should create a known-issues in docs? I will propose to use Sphinx to generate docs. I'll create a new issue about it.

**Comment by goanpeca** [comment]
Sure, I think that would be sweet :-)
