### ISSUE TITLE
v2.6.6+ update now show lines around labels

### ISSUE THREAD

**Issue by marcelomanzo** [ColinDuquesnoy/QDarkStyleSheet#141]
I'm using python 3.7 and the latest version from the repository.

This week, when I compiled my app this week it started showing lines around the labels
![image](https://user-images.githubusercontent.com/12878783/56849700-b968a600-68c5-11e9-986c-29685d24c652.png)

**Comment by marcelomanzo** [comment]
I am using pyside 2

**Comment by dpizetta** [comment]
Please, run qdarkstyle --all and send the information. Tks

**Comment by marcelomanzo** [comment]
Information about your current environment setup:
  - QDarkStyle: 2.6.6
  - OS: Windows 10 AMD64
  - Platform: win32
  - Python: 3.6.5.final.0
  - Python API: 1013
  - Binding in use:     Not set or nonexistent
  - Abstraction in use: Not set or nonexistent
  - qtpy (QT_API):                Not set or nonexistent
  - pyqtgraph (PYQTGRAPH_QT_LIB): Not set or nonexistent
  - Qt.py (__binding__):          Not set or nonexistent

Qt bindings available:
  - PySide2

Qt abstraction layers available:
