### ISSUE TITLE
Create svg files for all images used in rc

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#149]
As we started using scripts to process images from svg files to programmatically change colors, we need - also for quality images, svg files for all images. I'll provide it.

- [X] Provide svg for all resources used within a standard ([KDE](https://hig.kde.org/style/icon.html), [Material](https://material.io/design/iconography/product-icons.html#grid-keyline-shapes));
- [ ] Standardize resources names updating qsass, qrc, qss;

**Comment by goanpeca** [comment]
Are we using some minimal HIC guide?

Something like https://hig.kde.org/style/icon.html ?

**Comment by dpizetta** [comment]
Not until know, but we can use for sure. 

I personally use this reference for my work: [Material ](https://material.io/design/iconography/product-icons.html#grid-keyline-shapes).

**Comment by goanpeca** [comment]
Sure that one works ;-) although more oriented to web and mobile than "traditional" desktop

**Comment by dpizetta** [comment]
@goanpeca some questions, I've finished all svg files, however:

- We keep all svg images in the same size, e.g, 32x32px? For example, vertical line is 32x6px.
- The official size can be given in the style file in the case of proportion, e.g. 32x32px in the file, but using 12x12px for arrows for example. So we keep these files also with the same size?

The old rc files:
![image](https://user-images.githubusercontent.com/5084939/58287399-50226880-7d87-11e9-9ac5-8352ddfc20fd.png)

A big refactoring will be need to set all names. Using general_specific_action/state/etc, see below.
![image](https://user-images.githubusercontent.com/5084939/58287051-7abff180-7d86-11e9-916d-d957fdcd514e.png)

![image](https://user-images.githubusercontent.com/5084939/58287906-9a581980-7d88-11e9-9c03-4eaf56033d6f.png)

**Comment by goanpeca** [comment]
I would like to hace a fixed size if possible. Also depending on what the minimum size we aim for 24, 16, 32 ? We could make the images pixel perfect.

The standarized names is a welcome change :-)

**Comment by goanpeca** [comment]
Actually I think there is a reason for the dimensions of files that are not squared, so probably we need to keep those the same, with one side being 32 and the other whatever is needed to make the application look good.

The arrows are now looking weird on the file explorer (See the PR comment)

**Comment by dpizetta** [comment]
See PR #173 discussion. Closing this as they are added in the PR.
