### ISSUE TITLE
Vertical Slider Bars Colors inverted

### ISSUE THREAD

**Issue by marcelomanzo** [ColinDuquesnoy/QDarkStyleSheet#150]
The blue line of the vertical sliders bars is inverted, when you compare with the horizontal one, the blue portion is on the min side.

The vertical on the other hand has gray on the min side.

![image](https://user-images.githubusercontent.com/12878783/57072596-3fad2f80-6cac-11e9-9df0-95c1b9d5a496.png)

**Comment by marcelomanzo** [comment]
Information about your current environment setup:

QDarkStyle: 2.6.6
OS: Windows 10 AMD64
Platform: win32
Python: 3.6.5.final.0
Python API: 1013
Binding in use: Not set or nonexistent
Abstraction in use: Not set or nonexistent
qtpy (QT_API): Not set or nonexistent
pyqtgraph (PYQTGRAPH_QT_LIB): Not set or nonexistent
Qt.py (binding): Not set or nonexistent
Qt bindings available:

PySide2
Qt abstraction layers available:

**Comment by dpizetta** [comment]
TKS for reporting, nice catch.

**Comment by marcelomanzo** [comment]
issue still persists...

![image](https://user-images.githubusercontent.com/12878783/57982525-8a50da80-7a14-11e9-81d7-96ea4821bb69.png)

(srsvenv) C:\temp\srsvenv\Scripts>qdarkstyle --all
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Windows
    - Release....................... 10
    - Platform...................... Windows-10-10.0.17763-SP0
    - Version....................... 10.0.17763
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.7.0
    - C Compiler.................... MSC v.1914 64 bit (AMD64)
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.7.0
* QT BINDINGS--------------------------------------------------------------------
    - PySide2 Version............... 5.12.3
    - PySide2 Qt Version............ 5.12.3
* QT ABSTRACTIONS----------------------------------------------------------------
    - Status........................ No Qt abstractions available!
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.6.10

**Comment by marcelomanzo** [comment]
this is the correct compiled version for reference

QSlider --------\
----------------\
----------------\
----------------\
-------- */\x0a\x0aQSl\
ider:disabled {\x0a\
    background: \
#19232D;\x0a}\x0a\x0aQSli\
der:focus {\x0a    \
border: none;\x0a}\x0a\
\x0aQSlider::groove\
:horizontal {\x0a  \
  background: #3\
2414B;\x0a    borde\
r: 1px solid #32\
414B;\x0a    height\
: 4px;\x0a    margi\
n: 0px;\x0a    bord\
er-radius: 4px;\x0a\
}\x0a\x0aQSlider::sub-\
page:horizontal \
{\x0a    background\
: #1464A0;\x0a    b\
order: 1px solid\
 #32414B;\x0a    he\
ight: 4px;\x0a    m\
argin: 0px;\x0a    \
border-radius: 4\
px;\x0a}\x0a\x0aQSlider::\
sub-page:horizon\
tal:disabled {\x0a \
   background: #\
14506E;\x0a}\x0a\x0aQSlid\
er::handle:horiz\
ontal {\x0a    back\
ground: #787878;\
\x0a    border: 1px\
 solid #32414B;\x0a\
    width: 8px;\x0a\
    height: 8px;\
\x0a    margin: -8p\
x 0;\x0a    border-\
radius: 4px;\x0a}\x0a\x0a\
QSlider::handle:\
horizontal:hover\
 {\x0a    backgroun\
d: #148CD2;\x0a    \
border: 1px soli\
d #148CD2;\x0a}\x0a\x0aQS\
lider::groove:ve\
rtical {\x0a    bac\
kground: #1464A0\
;\x0a    border: 1p\
x solid #32414B;\
\x0a    width: 4px;\
\x0a    margin: 0px\
;\x0a    border-rad\
ius: 4px;\x0a}\x0a\x0aQSl\
ider::sub-page:v\
ertical {\x0a    ba\
ckground: #32414\
B;\x0a    border: 1\
px solid #32414B\
;\x0a    width: 4px\
;\x0a    margin: 0p\
x;\x0a    border-ra\
dius: 4px;\x0a}\x0a\x0aQS\
lider::sub-page:\
vertical:disable\
d {\x0a    backgrou\
nd: #14506E;\x0a}\x0a\x0a\
QSlider::handle:\
vertical {\x0a    b\
ackground: #7878\
78;\x0a    border: \
1px solid #32414\
B;\x0a    width: 8p\
x;\x0a    height: 8\
px;\x0a    margin: \
0 -8px;\x0a    bord\
er-radius: 4px;\x0a\
}\x0a\x0aQSlider::hand\
le:vertical:hove\
r {\x0a    backgrou\
nd: #148CD2;\x0a   \
 border: 1px sol\
id #148CD2;\x0a}\x0a\x0a/\

**Comment by goanpeca** [comment]
Will take a look at this @dpizetta @marcelomanzo

**Comment by dpizetta** [comment]
@marcelomanzo could you run the example  that is in example/example.py and check the slides there also? TKS

**Comment by marcelomanzo** [comment]
Works like a charm:
pip install git+git://github.com/ColinDuquesnoy/QDarkStyleSheet.git@d553852b5de6b1c3de7f04f8c792ef4f3b49d776

![image](https://user-images.githubusercontent.com/12878783/58092344-d711ee00-7b99-11e9-8bc6-9361f82f9336.png)

**Comment by dpizetta** [comment]
Nice!
