### ISSUE TITLE
Add ability to create new custom palette programmatically at runtime

### ISSUE THREAD

**Issue by goanpeca** [ColinDuquesnoy/QDarkStyleSheet#151]
- Embed sass and svg files in the resources
- Write sass and svg files from qrc to a temp directory (or user selected dir)
- Generate qss and png files in the temp directory (or user selected dir)
- Replace qrc:// url in the stylesheet by the temp directory (or user selected dir)
- Load the stylsheet from the temporary dir (or user selected dir) instead of the the qrc file.

**Comment by dpizetta** [comment]
I'd add also as a second step a GUI (later I'll post a mock-up) with:

* "Palette image" as the palette.svg to click and change colors (9) of named parts (i.e variables from sass) ;
* Other variables such as border-radius;
* Preloaded palettes to be chosen - as it is not so simple to match the colors that provide a good contrast - it is simplified with the "palette image" but still not so simple;

So this GUI can also be attached to user's program to customize the interface if interesting. The "example" can be run aside to check eventual problems.

**Comment by dpizetta** [comment]
Just to make a reference #143 as we need to reload :)
