### ISSUE TITLE
Update contribute guide to incorporate qsass, new scripts and instructions

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#153]
[  ] Add qsass information (@goanpeca could you take care of this one?);
[  ] Add new scripts explanations;
[  ] Review guide;

**Comment by goanpeca** [comment]
>add qsass information (@goanpeca could you take care of this one?);

@dpizetta, sure, where do  you want this updated?

**Comment by dpizetta** [comment]
I think, for now, here https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/CONTRIBUTING.md#modifying-qss-file
then I can move this file internally to docs. Thus, we keep only the main files over the repo root.

Tks!
