### ISSUE TITLE
QAbstractScrollArea padding clips text

### ISSUE THREAD

**Issue by SomberNight** [ColinDuquesnoy/QDarkStyleSheet#159]
Using QDarkStyle 2.6.8, PyQt 5.11.3, cpython 3.6.6, on Windows 10.

Text is getting clipped in this QPlainTextEdit:
![img1](https://user-images.githubusercontent.com/29142493/57186091-52f11280-6ed9-11e9-97ed-3adde03395f8.PNG)
Text also getting clipped here. Not sure what Qt element it is, it belongs to a QCompleter.
![img2](https://user-images.githubusercontent.com/29142493/57186094-7fa52a00-6ed9-11e9-89ab-82407f0a36c1.png)

Issue does not affect QDarkStyle 2.5.4, on the same system.

Also tested on Ubuntu 18.04 (with GNOME), PyQt 5.11.3, cpython 3.6.7.
There is less clipping there but still some.
![img3](https://user-images.githubusercontent.com/29142493/57186146-28538980-6eda-11e9-9c90-d05e1b85fc3a.PNG)

-----

I've tracked this down; and it is because of the padding of QAbstractScrollArea:
https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/6958bf798fb97314d3928ebce548e3de20e367ff/qdarkstyle/style.qss#L485-L489

**Comment by goanpeca** [comment]
Maybe we need to add a minimum height and still have padding?

Something like:

```css
 QAbstractScrollArea { 
   background-color: #19232D; 
   border: 1px solid #32414B; 
   border-radius: 4px; 
   padding: 4px;
   min-height: 1.5em;
...
```

**Comment by dpizetta** [comment]
@SomberNight  is this happening on older versions? Like 2.6.7, 2.6.6... Tks

**Comment by SomberNight** [comment]
@dpizetta Yes, it happens with all of 2.6.5,  2.6.6,  2.6.7

**Comment by dpizetta** [comment]
@SomberNight could you try this commit using 2px? Changing to 0px generate problems in the example also using min-height. Tks

**Comment by SomberNight** [comment]
I've tested with version 2.7 from PyPI. Seems to work. Thanks!
