### ISSUE TITLE
Lines around Qlabel in v2.6.8 & Python 3.7

### ISSUE THREAD

**Issue by kosayoda** [ColinDuquesnoy/QDarkStyleSheet#163]
### Environment

- QDarkStyle: 2.6.8
- OS: Linux 4.15.0-48-generic x86_64
- Python: 3.7.2.final.0
- PySide2: 5.12.3 

`qdarkstyle --all` throws an error, see #162 

### Language

Python

### Actual Result
![Screenshot from 2019-05-06 14-40-49](https://user-images.githubusercontent.com/41782385/57210422-2d662500-700f-11e9-8d4c-91d82476d97f.png)

Looks like #141 except the current version is 2.6.8, please advise if it's intended

**Comment by dpizetta** [comment]
It should be not like this. Could you provide your code or at least the nesting of items until the QLabel? Tks

**Comment by kosayoda** [comment]
The `.ui` file is generated using QtDesigner, then converted to a `.py` file. The Qt Designer Object Inspector looks like this:

![Screenshot from 2019-05-06 19-53-09](https://user-images.githubusercontent.com/41782385/57223520-f442aa80-7038-11e9-94a9-9c18b0759992.png)

My code looks like this (relevant portions):
```python
class MainApplication(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = ui.MainWindow()  # the generated Ui_MainWindow class
        self.ui.setupUi(self)

def main():
    app = QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyside2())
    window = MainApplication()
    window.show()
    sys.exit(app.exec_())
```

**Comment by dpizetta** [comment]
@goanpeca is the _style.scss updated with the last changes in style.qss? If so, I'll start to use it to not change the qss manually. 

To fix this may we need to use ".QFrame" instead of QFrame that includes descendants, including QLabel.

**Comment by goanpeca** [comment]
@dpizetta if you have `qtsass` installed then we should only work with the `_style.scss` file (which should include all the latest changes I found)

**Comment by dpizetta** [comment]
@goanpeca  Should I use the version 0.2.2 alpha from release or from master as it is not available on pypi yet?

**Comment by goanpeca** [comment]
this one is fine https://pypi.org/project/qtsass/

**Comment by dpizetta** [comment]
I was not up to date :) Tks

**Comment by dpizetta** [comment]
@kosayoda could you test this branch? Remember to remove the old installation before. Tks

`git clone -b fix-qlabel-lines-frame https://github.com/ColinDuquesnoy/QDarkStyleSheet.git qdark-fix-qlabel`

**Comment by kosayoda** [comment]
Was testing it just as this issue got closed, just commenting for posterity.
I can confirm that the branch fixes the issue. Thank you for the fix.

**Comment by dpizetta** [comment]
Tks!
