### ISSUE TITLE
Move files to utils?

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#164]
In my opinion, we should move some files:

- process_qrc.py > qdarkstyle/utils/qrc.py (compile qrc)
- palette.py > qdarkstyle/utils/palette.py (check palette contrast)

Because they are required if you want to generate the files by yourself up to compiled.

And these ones, if wanted to check a standard example window.

- process_ui.py > qdarkstyle/utils/ui.py
- run_ui_css_edition.py > qdarkstyle/utils/ui_style_edition.py
- example > qdarkstyle/example

Also, should we provide the 'example' to run the ui_style_edition.

@ColinDuquesnoy  @goanpeca opinions?

**Comment by goanpeca** [comment]
Hi @dpizetta I agree with all your suggestions

**Comment by goanpeca** [comment]
The only thing to keep in mind is that for conda packages there will be no qtsass (no libsass) available for windows py27 so all that toolchain will not be available for that specific case.

With pypi there should not be a problem. 

They will be able to still use the package normally but no custom palette creation at runtime.

**Comment by dpizetta** [comment]
Since py27 is going to die soon, I think that there is no problems. As well as py34 will too.  Things after py36 are much better for qt things as we can simple install pyqt/pyside from pypi. Actually, I was propose to us to keep some dates/versions of compatible python distribution. Many things we can't do with py27.

**Comment by dpizetta** [comment]
Implemented in v3.0
