### ISSUE TITLE
QTableView Hover color

### ISSUE THREAD

**Issue by ben-hearn-sb** [ColinDuquesnoy/QDarkStyleSheet#166]
When hovering over a QTableView only column hovering is supported. I have my QTableView set to QAbstractItemView.SelectRows but only hovered columns are supported

Is there a way to edit this easily?

// Ben

**Comment by goanpeca** [comment]
@ben-hearn-sb could you please psot some screenshots of what you would like to achieve?

**Comment by ben-hearn-sb** [comment]
Yes, I will post up screenshots later today

**Comment by ben-hearn-sb** [comment]
<img width="646" alt="Screen Shot 2019-05-08 at 7 46 26 PM" src="https://user-images.githubusercontent.com/13691166/57396146-030c9700-71ca-11e9-96f1-40294ae39c19.png">

My selection mode for my table is row selection yet the hover highlight is single cell based only. This confused the selection mode across the tool

**Comment by goanpeca** [comment]
I do not think this is possible with QSS

**Comment by ben-hearn-sb** [comment]
There seems to be a solution here although not sure how easy or not easy it is to implement:
https://github.com/lowbees/Hover-entire-row-of-QTableView/blob/master/styleditemdelegate.cpp

**Comment by goanpeca** [comment]
That requires coding so no qss only solution on our side.

**Comment by ben-hearn-sb** [comment]
ah ok I see, I will try and find another solution. Thank you anyway :)
