### ISSUE TITLE
Example is not working with the option --no_dark

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#167]
### Describe Your Environment

* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Linux
    - Release....................... 4.15.0-48-generic
    - Platform...................... Linux-4.15.0-48-generic-x86_64-with-debian-buster-sid
    - Version....................... #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.6.8
    - C Compiler.................... GCC 7.3.0
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.6.8
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.12.1
    - PyQt5 Qt Version.............. 5.12.2
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.7.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
    - pyqtgraph Version............. 0.10.0
    - pyqtgraph Binding............. Not set or inexistent
    - pyqtgraph Binding Variable.... os.environ['PYQTGRAPH_QT_LIB']
    - pyqtgraph Import Name......... pyqtgraph
    - pyqtgraph Status.............. OK
### Language

[Python]

### Description / Steps to Reproduce [if necessary]

It seems to be after the last updates on rep over the example folder.

Execute 

`python example/example.py --no_dark`

### Actual Result

Dark themed

### Expected Results / Proposed Result

Not dark

**Comment by goanpeca** [comment]
Hmmmm oops 😬
