### ISSUE TITLE
Lines around Qlabel when using QInputDialog

### ISSUE THREAD

**Issue by marcelomanzo** [ColinDuquesnoy/QDarkStyleSheet#168]
![image](https://user-images.githubusercontent.com/12878783/57493549-61517c80-7293-11e9-8309-f4298c90e8e1.png)

Information about your current environment setup:

QDarkStyle: 2.6.6
OS: Windows 10 AMD64
Platform: win32
Python: 3.6.5.final.0
Python API: 1013
Binding in use: Not set or nonexistent
Abstraction in use: Not set or nonexistent
qtpy (QT_API): Not set or nonexistent
pyqtgraph (PYQTGRAPH_QT_LIB): Not set or nonexistent
Qt.py (binding): Not set or nonexistent
Qt bindings available:

PySide2
Qt abstraction layers available:

**Comment by dpizetta** [comment]
Could you try version 2.6.8 and check is it still happening? Tks

**Comment by marcelomanzo** [comment]
2.6.8 still same issue:
![image](https://user-images.githubusercontent.com/12878783/57979440-a5f3bb00-79eb-11e9-807f-91cace32e5ac.png)

**Comment by dpizetta** [comment]
We need to change qlabel in the rcc to .qlabel, so it gets all qlabel nested classes.  I will try later night.tks

**Comment by dpizetta** [comment]
Same as #163

**Comment by dpizetta** [comment]
@marcelomanzo  could you test this branch? Remember to remove the old installation before. Tks

`git clone -b fix-qlabel-lines-frame https://github.com/ColinDuquesnoy/QDarkStyleSheet.git qdark-fix-qlabel`

**Comment by marcelomanzo** [comment]
works like a charm, thanks!
![image](https://user-images.githubusercontent.com/12878783/58092265-ad58c700-7b99-11e9-94cd-aa81daa278dd.png)
