### ISSUE TITLE
Styling a Line from Designer

### ISSUE THREAD

**Issue by MHendricks** [ColinDuquesnoy/QDarkStyleSheet#17]
QDarkStyleSheet is a really nice stylesheet. I ran into a unstyled "widget", the "Horizontal Line" and "Vertical Line" in Qt Designer. [It is a QFrame with height 3, sunken shadow and line width equal to 1. You can see it if examine header generated by uic tool.](http://stackoverflow.com/a/13930601)

    QFrame[isLine="true"] {
        background-color: #3A3939;
    }

The only way I can think to style it is to add a bool QProperty and use a dynamic property selector in the stylesheet. This is not the best solution because you have to remember to add the property every time.

    QFrame[height="3"], QFrame[width="3"] {
        background-color: #3A3939;
    }

Now that I'm typing this issue up, I thought of a second way to handle it, by checking if the width or height is 3 on qframes.

I don't know if either of these should be included in QDarkStyleSheet, but its worth mentioning in case someone has a better idea.

**Comment by ColinDuquesnoy** [comment]
I've tried your second suggestion and it works like a charm (on KDE). It will be included in the next release. Thanks for sharing!
