### ISSUE TITLE
Util package should not be imported in ordinary qdarkstyle usage

### ISSUE THREAD

**Issue by marcelomanzo** [ColinDuquesnoy/QDarkStyleSheet#170]
### Describe Your Environment
(srsvenv) C:\temp\srsvenv\Scripts>qdarkstyle --all
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Windows
    - Release....................... 10
    - Platform...................... Windows-10-10.0.17763-SP0
    - Version....................... 10.0.17763
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.7.0
    - C Compiler.................... MSC v.1914 64 bit (AMD64)
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.7.0
* QT BINDINGS--------------------------------------------------------------------
    - PySide2 Version............... 5.12.3
    - PySide2 Qt Version............ 5.12.3
* QT ABSTRACTIONS----------------------------------------------------------------
    - Status........................ No Qt abstractions available!
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.6.10

### Language

[Python]

### Description / Steps to Reproduce [if necessary]
Invoke:
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyside2())
### Actual Result

  File "C:\Users\marce\PycharmProjects\dashboard\gui\gui.py", line 86, in main
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyside2())
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\__init__.py", line 355, in load_stylesheet_pyside2
    return load_stylesheet(pyside=True)
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\__init__.py", line 272, in load_stylesheet
    from qdarkstyle.utils.scss import create_qss
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\utils\scss.py", line 24, in <module>
    from qdarkstyle.utils.images import create_images, create_palette_image
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\utils\images.py", line 14, in <module>
    from qtpy.QtCore import QSize
ModuleNotFoundError: No module named 'qtpy'
### Expected Results / Proposed Result

[A description, output ou image of the expected/proposed result]

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```
# code here to reproduce the problem
```

**Comment by ccordoba12** [comment]
> ModuleNotFoundError: No module named 'qtpy'

You don't `qtpy` installed, which is a dependency of QDarkstyie.

**Comment by marcelomanzo** [comment]
This is strange, why would I install pyqt if I'm using pyside2?
It wasn't like this 3 weeks ago.

**Comment by goanpeca** [comment]
`qtpy != pyqt`

**Comment by marcelomanzo** [comment]
ok, let me try

**Comment by marcelomanzo** [comment]
Now I get:
C:\temp\srsvenv\Scripts\python.exe C:/Users/marce/PycharmProjects/dashboard/main.py
Traceback (most recent call last):
  File "C:/Users/marce/PycharmProjects/dashboard/main.py", line 18, in <module>
    gui.gui.main()
  File "C:\Users\marce\PycharmProjects\dashboard\gui\gui.py", line 86, in main
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyside2())
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\__init__.py", line 355, in load_stylesheet_pyside2
    return load_stylesheet(pyside=True)
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\__init__.py", line 273, in load_stylesheet
    create_qss()
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\utils\scss.py", line 108, in create_qss
    _create_scss_variables(variables_scss_filepath, palette)
  File "C:\temp\srsvenv\lib\site-packages\qdarkstyle\utils\scss.py", line 82, in _create_scss_variables
    with open(variables_scss_filepath, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\temp\\srsvenv\\lib\\site-packages\\qdarkstyle\\qss\\_variables.scss'

![image](https://user-images.githubusercontent.com/12878783/57982707-1532d480-7a17-11e9-8388-218fec4bc844.png)

**Comment by ccordoba12** [comment]
@goanpeca?

**Comment by goanpeca** [comment]
@marcelomanzo what version of QDarkStyle are you using?

**Comment by marcelomanzo** [comment]
pip install git+git://github.com/ColinDuquesnoy/QDarkStyleSheet.git

**Comment by goanpeca** [comment]
Is there any reason why you are using master instead of doing?

```
pip install QDarkStyleSheet
```

**Comment by marcelomanzo** [comment]
I was checking if the  #150 was fixed  in the master but not in the repository.

**Comment by goanpeca** [comment]
@ccordoba12, doing a `open` with `w` flag does not create the file if not existent?

`with open(variables_scss_filepath, 'w') as f:` I do not understand why that error is there

**Comment by goanpeca** [comment]
@marcelomanzo You need to reinstall, since what you have does not seem to correspond to what is currently on master

https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/qdarkstyle

<img width="977" alt="Screen Shot 2019-05-19 at 09 00 03" src="https://user-images.githubusercontent.com/3627835/57983176-84f39000-7a14-11e9-832c-e551a62fd1fc.png">

You are missing a bunch of folders...

**Comment by marcelomanzo** [comment]
ok, you can close, would you be able to re-open #150?

thanks

**Comment by dpizetta** [comment]
Hi @goanpeca @ccordoba12  May we have to not import from "util" in the __init__, as we have discussed that we'll still be producing the qss file to put in the repo, and at this moment qtpy is only needed for developers or for who wants to change something in the style. And remembering that to compile, people need to have other tools like uic/rcc that could depends on not only Python.

```
from __init__.py line 275

# Compiles SCSS/SASS files to QSS
    from qdarkstyle.utils.scss import create_qss
    create_qss()
```

**Comment by goanpeca** [comment]
@dpizetta sure, we can add those imports with `try/except` 

If you can open an issue I can look at ti :-)

**Comment by dpizetta** [comment]
As the main problem in this issue as not about PySide2, I've changed the title, so we have a case of use.

**Comment by dpizetta** [comment]
@goanpeca  If you have not worked on it yet, I can make those changes :) Could you take a look in the current version on repo if they are ok with both example interface and spyder? So we can create a new release :) Tks

**Comment by goanpeca** [comment]
I am out right now, I can do it tomorrow! (sorry I forgot about this issue :-|, if you could work on it that would be great!

**Comment by dpizetta** [comment]
No problems, I take care!

**Comment by marcelomanzo** [comment]
it's working now, thanks!
