### ISSUE TITLE
Load file dialog is not styled

### ISSUE THREAD

**Issue by SteveDoyle2** [ColinDuquesnoy/QDarkStyleSheet#172]
### Describe Your Environment

Please, report the output of the command:

`$ qdarkstyle --all`

Information about your current environment setup:
  - QDarkStyle: 2.6.8
  - OS: Windows 10 AMD64
  - Platform: win32
  - Python: 3.7.3.final.0
  - Python API: 1013
  - Binding in use:     Not set or nonexistent
  - Abstraction in use: Not set or nonexistent
  - qtpy (QT_API):                Not set or nonexistent
  - pyqtgraph (PYQTGRAPH_QT_LIB): Not set or nonexistent
  - Qt.py (__binding__):          Not set or nonexistent

Qt bindings available:
  - PyQt5
  - PySide2

Qt abstraction layers available:
  - qtpy

[If used, please inform their versions]

- PySide2: 5.12.2 (used)
- PyQt: 5.12.2 (unused)
- PyQtGraph: N/A
- QtPy: 1.7.0
- QT_API:  N/A
- PYQTGRAPH_QT_LIB: N/A

### Language

Python

### Description

It appears that the load file dialog is not themed.  All of the other menu types I've checked look great.

### Actual Result

![image](https://user-images.githubusercontent.com/1059417/58357992-deebbf80-7e31-11e9-8caa-0964e9d075f4.png)

**Comment by goanpeca** [comment]
Hi @SteveDoyle2 thanks for reporting. I am guessing you are using the static methods?

https://doc.qt.io/qt-5/qfiledialog.html#static-public-members ?

What happens if you create an instance first https://doc.qt.io/qt-5/qfiledialog.html#QFileDialog
And then click show() /exec_() ?

**Comment by goanpeca** [comment]
Thanks for reporting @SteveDoyle2. Now, these dialogs are systems dialogs defined by the operating system, so there is no way for them to be styled with this theme unless you create your own custom file dialogs

**Comment by dpizetta** [comment]
May you have to use, if not using, this option "DontUseNativeDialog". It seems that the dialog is opening from the native OS dialog (default behavior), which could be not themed.

Take a look: https://doc.qt.io/qt-5/qfiledialog.html#Option-enum

Tip: You can use in your Log Window the blue: R:0  G:51  B:78 which will give you better readability. Also matching with this red: R:96  G:33  B:36 - more like pastel colors. Tks

**Comment by goanpeca** [comment]
Also, since you are probably using the static methods to all these dialogs, you cannot style them.

Perhaps trying 
```
dialog = QFileDialog(...)
dialog.setStyleSheet(...) 
dialog.show()
```

**Comment by SteveDoyle2** [comment]
Ahhh...that makes sense.  I tried the first option, which works, but the Windows Explorer aspect is lost.  The second doesn't quite work with my code as I'm using qtpy's getopenfilename method.

I'll play around with it, but thank you!  This is a very well done theme.

**Comment by dpizetta** [comment]
@goanpeca could you add this issue to [ known-issues](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/develop/docs/known_issues.rst)? Tks :)

**Comment by goanpeca** [comment]
I think this not really an issue. I think it is expected that when using OS system dialogs they should look like the OS mandates.

**Comment by dpizetta** [comment]
Oh, yeah, I agree, but this may avoid users asking about it. Do you think worth it to write about? If not, we can close this issue :) Tks

**Comment by goanpeca** [comment]
Hmm ok yes in that case it makes sense where should I write about this?

**Comment by dpizetta** [comment]
We have a file for known issues in docs https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/develop/docs/known_issues.rst :)
