### ISSUE TITLE
Toggle icons are impossible to tell when enabled if the background color is the same as the button

### ISSUE THREAD

**Issue by CAM-Gerlach** [ColinDuquesnoy/QDarkStyleSheet#176]
Opened on the direct request of @dpizetta .

If the background color of a pane happens to be the same as the button color, It is almost impossible to tell if toggle buttons are enabled or disabled, and they appear to be reversed from what a user might expect. Example:

Disabled:

![image](https://user-images.githubusercontent.com/17051931/57481142-761c1900-726f-11e9-836b-af5a2ba1d86f.png)

Enabled:

![image](https://user-images.githubusercontent.com/17051931/57481165-8502cb80-726f-11e9-8792-209e5e86edba.png)

Therefore, it would seem prudent to e.g. outline them in a much thicker, brighter white or blue when enabled, or even color the icon blue to indicate the button is toggled on.

**Comment by dpizetta** [comment]
@CAM-Gerlach could you point to me in which widget is that buttons are (a piece of code would be useful too)? Ex. Inside qtabbar. Because I will change just this specific case to not match with the toolbar buttons. Tks

**Comment by goanpeca** [comment]
(The find/replace widget of the Spyder editor)
