### ISSUE TITLE
Tristate checkboxes not supported

### ISSUE THREAD

**Issue by fieldOfView** [ColinDuquesnoy/QDarkStyleSheet#18]
A QCheckbox with Tristate set to True renders the same, whether its CheckState is Unchecked or PartiallyChecked. The two states should be visually distinguishable.

**Comment by ColinDuquesnoy** [comment]
I believe this issue has already been fixed by PR #16 but I haven't released it yet on pypi. May I ask you to try directly from the master branch.

**Comment by fieldOfView** [comment]
I tried the master branch before, but only just noticed that the py*_style_rc.py files need to be recompiled.

**Comment by ColinDuquesnoy** [comment]
Ah yes you're right. I'll try to find some time to recompile them during the weekend and upload a new release on pypi. Thank you for reporting!

**Comment by ColinDuquesnoy** [comment]
Should be fixed now, see

![state11](https://cloud.githubusercontent.com/assets/1681217/5682986/70b426ee-9824-11e4-8b6c-2a040fe2d968.png)

![state12](https://cloud.githubusercontent.com/assets/1681217/5682992/7e109386-9824-11e4-84f1-75d2a75b454a.png)

Going to release it on pypi soon.

**Comment by fieldOfView** [comment]
Awesome. Might I suggest a tweak in the graphics though? Currently if you see a UI where the only checkbox is a partially checked tristate checkbox, you might still recognise it as fully checked untill you click it and see there's a fuller check.

A dimmed square or a dimmed dash instead of the current dimmed cross sets the partiallychecked checkbox apart from the other two states and makes it immediately clear that it is not a (fully) checked checkbox.

I can create a pullrequest with a tweaked graphic if you wish.

**Comment by ColinDuquesnoy** [comment]
> I can create a pullrequest with a tweaked graphic if you wish.

Yeah sure! That would be awesome!

**Comment by fieldOfView** [comment]
The above referenced pullrequest implements a dash. I can also do a square, which is more in line with the standard behavior in Windows. The advantage of the dash is that is is less likely to be confused for an unchecked checkbox.

![untitled-1](https://cloud.githubusercontent.com/assets/143551/5688632/0339ea32-985a-11e4-88b6-5fc2d718e87f.png)
