### ISSUE TITLE
Toolbuton size without border is smaller then with border causing UI misalignment and flickering

### ISSUE THREAD

**Issue by jnsebgosselin** [ColinDuquesnoy/QDarkStyleSheet#181]
I think the changes introduced in https://github.com/ColinDuquesnoy/QDarkStyleSheet/commit/7d1eab947d758ef6a773c48e36feabd3245b8160 is a nice improvement.

However, now buttons without a border are smaller than those with a border, so this cause some misalignment in the UI.

Also, it cause some flickering of the icon and label position when hovering the mouse over the button due to the UI adjusting to the change of size when the border is or is not present.

![iconsize](https://user-images.githubusercontent.com/10170372/58832319-b2e3f180-861c-11e9-9395-740c527d35c3.gif)

**Comment by dpizetta** [comment]
Oh, OK, I'll fix it. Tks

**Comment by jnsebgosselin** [comment]
@dpizetta To solve this, you need to add `border: 1px solid transparent;` to the stylesheet of the Toolbutton. 

```
QToolButton {
  background-color: transparent;
  border: 1px solid transparent;
  border-radius: 4px;
  margin: 0px;
  padding: 2px;
  /* The subcontrols below are used only in the DelayedPopup mode */
  /* The subcontrols below are used only in the MenuButtonPopup mode */
  /* The subcontrol below is used only in the InstantPopup or DelayedPopup mode */
}
```

**Comment by dpizetta** [comment]
@jnsebgosselin tks, I'll add soon!
