### ISSUE TITLE
Helpdev package became a mandatory dependency, make it optional

### ISSUE THREAD

**Issue by SomberNight** [ColinDuquesnoy/QDarkStyleSheet#182]
The `helpdev` package was introduced as a mandatory dependency for 2.7, in https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/147
Along with `helpdev`, this pulls in `importlib-metadata`, `psutil`, and `zipp` as indirect dependencies.

It seems to me that `helpdev` is only used for diagnostics/bug reports.
Would it be possible to turn it into an optional dependency instead?

**Comment by dpizetta** [comment]
We can study this in the v2.8, as we will introduce qtpy as mandatory to simplify many things in the code (as seen in the develop branch). As we won't use directly the bindings, the other functions of helpdev won't be needed except for reports.
