### ISSUE TITLE
QTextEdit inside tabs not displaying border

### ISSUE THREAD

**Issue by goanpeca** [ColinDuquesnoy/QDarkStyleSheet#188]
### Describe Your Environment

Please, report the output of the command (from v2.6+) or fill the information below:

`$ qdarkstyle --all`

Or use the helpdev if you have

`$ helpdev`

[Versions from your environment]

- QDarkStyle: 2.7
- OS: OSX
- Python: 3.7

[If used, please inform their versions]

- PySide:
- PyQt:
- PyQtGraph:
- QtPy:
- QT_API:
- PYQTGRAPH_QT_LIB:

### Language

[Python] or [C++]

### Description / Steps to Reproduce [if necessary]

[Description of the issue]

QTextEdit inside Spyder preferences have no border, see animation

### Actual Result

![border](https://user-images.githubusercontent.com/3627835/59403874-1df29e00-8d6a-11e9-8cec-d932620050b6.gif)

### Expected Results / Proposed Result

The text edit box should have a border

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```
# code here to reproduce the problem
```

**Comment by dpizetta** [comment]
@goanpeca Could you test the latest develop commit?  I've tested here but I got a different result from yours. May it is a mac issue too. I compared to line edit in the gif. Tks

![Peek 2019-06-13 15-44](https://user-images.githubusercontent.com/5084939/59459109-66ee3500-8df2-11e9-8c91-0aa0f9ce81c5.gif)

**Comment by goanpeca** [comment]
I will check with develop @dpizetta thanks!

**Comment by goanpeca** [comment]
@dpizetta I am getting this error with latest `develop`

```python
python script/process_qrc.py 
Generating palette image ...
INFO:qdarkstyle.utils.images:Creating palette image ...
INFO:qdarkstyle.utils.images:Base SVG: /Users/gpena-castellanos/anaconda2/envs/spyder/lib/python2.7/site-packages/qdarkstyle/svg/base_palette.svg
INFO:qdarkstyle.utils.images:To SVG: /Users/gpena-castellanos/anaconda2/envs/spyder/lib/python2.7/site-packages/images/palette.svg
INFO:qdarkstyle.utils.images:To PNG: /Users/gpena-castellanos/anaconda2/envs/spyder/lib/python2.7/site-packages/images/palette.png
Traceback (most recent call last):
  File "script/process_qrc.py", line 191, in <module>
    sys.exit(main(sys.argv[1:]))
  File "script/process_qrc.py", line 91, in main
    run_process(args)
  File "script/process_qrc.py", line 100, in run_process
    create_palette_image()
  File "/Users/gpena-castellanos/anaconda2/envs/spyder/lib/python2.7/site-packages/qdarkstyle/utils/images.py", line 116, in create_palette_image
    with open(base_palette_svg_path, 'r') as fh:
IOError: [Errno 2] No such file or directory: '/Users/gpena-castellanos/anaconda2/envs/spyder/lib/python2.7/site-packages/qdarkstyle/svg/base_palette.svg'
```

**Comment by goanpeca** [comment]
@dpizetta with latest develop I can confirm that this is no longer an issue.

<img width="858" alt="Screen Shot 2019-06-18 at 11 47 35" src="https://user-images.githubusercontent.com/3627835/59703292-30803380-91bf-11e9-8b10-ec5bcb1aa91e.png">

**Comment by dpizetta** [comment]
Oh, great!

**Comment by dpizetta** [comment]
> It seems we are not packaging the svg/rc/qss folder. Is this on purpose?

At the beginning yes, because we have already put compiled files there, .qss and _rc.py. 

> We need to add this line to setup.py
> 
>     package_data={
>         'qdarkstyle': [
>             'svg/*.svg', 'rc/*.png', 'qss/*.scss',
>         ],
>     },
> Files are small enough that I think it is ok to package everything, no?

Another option is to include this if the package was installed with extras develop. I need to check if it is possible to differentiate those installations (as we will need the tools to work with it).

**Comment by dpizetta** [comment]
I'll open a new issue for the package_data and what we need to include.
