### ISSUE TITLE
Dropdown menus are not looking well in PyQt 5.12

### ISSUE THREAD

**Issue by ccordoba12** [ColinDuquesnoy/QDarkStyleSheet#191]
### Describe Your Environment

Please, report the output of the command (from v2.6+) or fill the information below:

- QDarkStyle: 2.7
- OS: Linux 
- Python: 3.6
- PyQt: 5.12
- QtPy: 1.8
- QT_API: pyqt5

### Language

Python

### Description / Steps to Reproduce [if necessary]

All entries in dropdown menus have a big blank space to its left when using PyQt 5.12

### Actual Result

![Selección_012](https://user-images.githubusercontent.com/365293/59671678-5b1dbc80-91be-11e9-8477-f5191bafd31f.png)

### Expected Results / Proposed Result

This is how things look in PyQt 5.9, which is fine

![Selección_013](https://user-images.githubusercontent.com/365293/59671837-a9cb5680-91be-11e9-8ba9-d6cb33cc783c.png)

**Comment by dpizetta** [comment]
Maybe related to #169 and/or including a patch in **_apply_version_patches()**. Could you take care of both @goanpeca? Tks @ccordoba12 

PS: those white corners are annoying. May some widget that has no border radius that is being expanded?

**Comment by goanpeca** [comment]
Hi @dpizetta I am checking this one out, to see what was the change on 5.12. Otherwise I will just use the combobox styledelegate fix on Spyder directly.

>PS: those white corners are annoying. May some widget that has no border radius that is being expanded?

Yeah, not sure what might be the issue here

**Comment by dpizetta** [comment]
Ok!

 > To be honest, I do not like the rounding of corners
Me too. They are tricky.

I keep the options for combo box without rounded corners like submenus. So, we can cover that problem.
