### ISSUE TITLE
Qt5.12.4 There may be problems.

### ISSUE THREAD

**Issue by X-Crack** [ColinDuquesnoy/QDarkStyleSheet#195]
Qt 5.12.4 

I don't know why.
I think this is very likely to be Qt's own bug.
But the problem does appear.
Can you solve it?

Debugging version
![1](https://user-images.githubusercontent.com/45416520/60588645-0edf9880-9dca-11e9-9fd4-4396abc8322f.png)
Release version
![2](https://user-images.githubusercontent.com/45416520/60588650-1010c580-9dca-11e9-885d-5f59b746a4c8.png)

**Comment by dpizetta** [comment]
Hi @X-Crack, do you still have this problem? As you said it should be Qt bug os some installation bug in your machine not rendering correctly. Tks

**Comment by dpizetta** [comment]
@X-Crack, any news about this issue? Could I close it?

**Comment by dpizetta** [comment]
Closed du the lack of communication and no more reported problems, reopen if needed.
