### ISSUE TITLE
Compatibility with custom widget with paintEvent

### ISSUE THREAD

**Issue by Daguerreo** [ColinDuquesnoy/QDarkStyleSheet#196]
I'm using [QxtSpanSlider](https://libqxt.bitbucket.io/doc/tip/qxtspanslider.html) in my project which is implemented with a custom paint event.

Using QDarkStyleSheet second handle disappear. I tried setting a null stylesheet to the slider and commenting the styelsheet for QSlider but it still does not render properly.

There is a way or a workaround to deal with custom widget?

**Comment by dpizetta** [comment]
Hi, we can not deal with those non-default widgets, but you can add to our stylesheet your piece of code that deals with the second handler. Look at this fix, that in your case you will add another widget.

```
fixedStyle = qdarkstyle.load_stylesheet_pyside2()
fixedStyle = fixedStyle + 
"""
QxtSpanSlider {
    &::handle {
        &:horizontal {
            background: red;
            border: $BORDER_NORMAL;
            width: 4px;
            height: 4px;
            margin: -8px 0px;
            border-radius: $SIZE_BORDER_RADIUS;
}}}
"""
```

Look at these lines to get an idea of what to do: https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/c92d0c4c996e3e859134492e0f9f7f74bd0e12cd/qdarkstyle/qss/_styles.scss#L1264

I hope it helps you! Tks

**Comment by maartenb72** [comment]
@Daguerreo: Did you eventually manage to get this working?
