### ISSUE TITLE
Darwin: QGroupBox title overlap QPushButton in VBoxLayout

### ISSUE THREAD

**Issue by nekopep** [ColinDuquesnoy/QDarkStyleSheet#20]
Hello,
Please find below a bug I saw using QDarkStyle under darwin.
"System to monitor" groupbox title overlaps QPushButton on top of it.

Gist:
https://gist.github.com/nekopep/84855cedbda300c5b383

![capture d ecran 2015-04-05 a 16 11 49](https://cloud.githubusercontent.com/assets/2825997/6997110/82982806-dbae-11e4-9653-13cdc207112a.png)

**Comment by nekopep** [comment]
Seems that adding padding-top could solve the issue: 

QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top center;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 10px;
}
![capture d ecran 2015-04-05 a 16 21 56](https://cloud.githubusercontent.com/assets/2825997/6997138/f5cbe488-dbaf-11e4-91f0-9f7077c0ba4a.png)

**Comment by ColinDuquesnoy** [comment]
Nice finding! I tested your fix on Linux but 10px is a bit too much here, 5px looks fine. Please check the latest commit on the master branch and let me know if that works for you.

**Comment by nekopep** [comment]
Hi colin,
5 px is too short on Mac.
![capture d ecran 2015-04-05 a 20 29 44](https://cloud.githubusercontent.com/assets/2825997/6998003/9f8ef2ea-dbd2-11e4-8211-1b2b7c74a9ba.png)
Moreover I think the issue come also from the padding of QGroupBox that is currently erroneous... (2ex)
Putting this is OK for me:

QGroupBox {
    border:1px solid #3A3939;
    border-radius: 7px;
    margin-top: 20px;
}

QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top center;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 15px;
}
![capture d ecran 2015-04-05 a 20 28 59](https://cloud.githubusercontent.com/assets/2825997/6998002/967f8e08-dbd2-11e4-9df1-08795797fe07.png)

**Comment by ColinDuquesnoy** [comment]
Indeed margin-top for QGroupBox was erroneous but the the padding-top set to 15 px is still too much here:

![github1](https://cloud.githubusercontent.com/assets/1681217/6998076/f4e77f76-dbd4-11e4-91ad-5b76f169dcd9.png)

This works for me:

QGroupBox {
    border:1px solid #3A3939;
    border-radius: 7px;
    margin-top: 20px;
}

QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top center;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 10px;
}

![github2](https://cloud.githubusercontent.com/assets/1681217/6998077/12310fc0-dbd5-11e4-8712-e6b3bdf5e513.png)

**Comment by nekopep** [comment]
Ok go with this. That's look ok on mac. By the way, here is a screenshot under win 8.1.
Looks like the Mac one is the one that is different form the two others anyway...
![capture d ecran 2015-04-05 a 21 43 31](https://cloud.githubusercontent.com/assets/2825997/6998315/e812436e-dbdc-11e4-8aee-9631fef87eb2.png)
