### ISSUE TITLE
Quick question about usage

### ISSUE THREAD

**Issue by MostHated** [ColinDuquesnoy/QDarkStyleSheet#201]
Hey there,
 I don't have any actual issue, I am just new to Qt. I was wondering if it's possible to use this package/style with the Go bindings for Qt? I started making an application using this https://github.com/therecipe/qt and while looking up examples of things I came across this repo and really liked the look, so I was just hoping it might be something I would be able to use. 

Thanks!
-MH

**Comment by dpizetta** [comment]
Hi, if you use just the stylesheet provided by our project, yes you can and most of widgets will be styled like ours. Some fixes are provided for specific cases and packages that you will need to handle if necessary, but it is less than 1% of work. Search by setting stylesheet using Qt, the best option. Tks

**Comment by MostHated** [comment]
No worries, I ended up switching over to using Flutter eventually. Appreciate you getting back to me, though.
