### ISSUE TITLE
The tabbar of 2.6.8 and tabbar of 2.7.0 is different if tabposition is west or east.

### ISSUE THREAD

**Issue by ok97465** [ColinDuquesnoy/QDarkStyleSheet#203]
### Describe Your Environment

* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Linux
    - Release....................... 4.20.17-1-MANJARO
    - Platform...................... Linux-4.20.17-1-MANJARO-x86_64-with-arch-Manjaro-Linux
    - Version....................... #1 SMP PREEMPT Tue Mar 19 18:07:36 UTC 2019
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.7.3
    - C Compiler.................... GCC 7.3.0
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.7.3
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.9.2
    - PyQt5 Qt Version.............. 5.9.6
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.5.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
    - pyqtgraph Version............. 0.10.0
    - pyqtgraph Binding............. Not set or inexistent
    - pyqtgraph Binding Variable.... os.environ['PYQTGRAPH_QT_LIB']
    - pyqtgraph Import Name......... pyqtgraph
    - pyqtgraph Status.............. OK
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.6.10
    - QDarkStyle.................... 2.7

### Actual Result

In 2.7.0
![스크린샷, 2019-07-28 21-19-09](https://user-images.githubusercontent.com/22970578/62006632-2c601200-b17e-11e9-8812-7702fd1fda15.png)

In 2.6.8
![스크린샷, 2019-07-28 21-19-33](https://user-images.githubusercontent.com/22970578/62006633-3124c600-b17e-11e9-890b-edb65545bb50.png)

### Expected Results / Proposed Result

[A description, output ou image of the expected/proposed result]

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```python
import sys
from qtpy.QtGui import QFont
from qtpy.QtWidgets import QMainWindow, QTabWidget, QApplication, QWidget
                            
import qdarkstyle
import qtawesome as qta


class MainWindowSAR(QMainWindow):
    def __init__(self):
        super().__init__()

        tab_widget = QTabWidget(self)
        tab_widget.setTabPosition(QTabWidget.East)
        tab_widget.addTab(QWidget(), qta.icon('fa5.flag', color='grey'), "flag")
        tab_widget.addTab(QWidget(), qta.icon('fa5s.music', color='grey'), "music")
        tab_widget.addTab(QWidget(), qta.icon('fa5s.camera', color='grey'), "camera")
        tab_widget.setMinimumWidth(200)
        tab_widget.setMinimumHeight(400)
       
        self.setCentralWidget(tab_widget)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())

    mainwindow = MainWindowSAR()

    mainwindow.show()

    sys.exit(app.exec_())
```

**Comment by dpizetta** [comment]
It is fixed in v2.8, look https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/develop/images/dark_containers_tabs_displays.png

Tks
