### ISSUE TITLE
Installation error with gcc

### ISSUE THREAD

**Issue by gokerguner** [ColinDuquesnoy/QDarkStyleSheet#204]
I've tried this package with "pip install qdarkstyle" command. Then, I take an error such as 
` /Users/goker/miniconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
`
What is the exact mean and how can I fix it?

**Comment by dpizetta** [comment]
It seems you are using C++ right, so you are not supposed to use pip install which is Python.

Try to follow the example we have in the README.

Also, you can post some pieces of your code to clarify what you are doing? Tks

**Comment by dpizetta** [comment]
Closing due to the lack of information.
