### ISSUE TITLE
White vertical lines between items of QStatusBar

### ISSUE THREAD

**Issue by dalthviz** [ColinDuquesnoy/QDarkStyleSheet#205]
### Actual Result
Basically when using the dark theme the lines are more visible (since they are white). With the light theme the lines are also visible but are light gray:

![image](https://user-images.githubusercontent.com/16781833/64629108-39486600-d3b8-11e9-87d8-94e8051c9ac3.png)

![image](https://user-images.githubusercontent.com/16781833/64629001-07cf9a80-d3b8-11e9-9e5a-52bc94c7557f.png)

_Originally posted by @dalthviz in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTk4NDgyODMwOnYy/pull_request_review_threads/discussion_

### Expected Results / Proposed Result

![image](https://user-images.githubusercontent.com/16781833/64707897-54c77580-d479-11e9-8adf-7b8c4e5f07da.png)

Following comment at https://github.com/spyder-ide/spyder/pull/10166#discussion_r322830569

**Comment by dpizetta** [comment]
Tks for sending us your feedback.
