### ISSUE TITLE
QSplitter::separator in style.css should probably be ::handle

### ISSUE THREAD

**Issue by Sonicsystem** [ColinDuquesnoy/QDarkStyleSheet#207]
Hello,

as the title says, I was confused about the fact that there was no visual representation of my QSplitter handle (maybe this is intended!)

I found out that the style.css uses the subcontrol QSplitter::separator, which according to the Qt documentation should not exist for a QSplitter and should be renamed to QSplitter::handle instead.

Reference - look at '::handle' in the following reference sheet: https://doc.qt.io/qt-5/stylesheet-reference.html.

### Versions used:

- PyQt5: 5.13.0
- QtPy: 1.9.0
- QDarkStyle: 2.7

### Language

Python

**Comment by dpizetta** [comment]
Thanks for your comments. I'll take a look.

**Comment by dpizetta** [comment]
I've changed the separator to handle, for correctness, but in our case, we are no showing the handle as all the splitter lights up when hover, but thanks for pointing that.
