### ISSUE TITLE
The style of active and non active items in table and list views is the same

### ISSUE THREAD

**Issue by jnsebgosselin** [ColinDuquesnoy/QDarkStyleSheet#209]
### Description

There is actually no distinction in the style of active and not active items in table and list views. Below is an example for the project plugin and keyboard shortcuts preference  dialog in Spyder using the darkstyle and windows vista style.

I think this would be a good idea to define a separate style for the not active items of table and list views.

![image](https://user-images.githubusercontent.com/10170372/68695232-a5765000-0548-11ea-9563-9b8d5f3e9ded.png)

![image](https://user-images.githubusercontent.com/10170372/68695382-ea01eb80-0548-11ea-89c1-58676002abdc.png)

**Comment by goanpeca** [comment]
@dpizetta with the upcoming release of spyder 4 it would be great to have a new release of QDark, any thoughts?

**Comment by dpizetta** [comment]
@goanpeca sorry for the late response. About the release, yes, we can schedule it for the end of this month, what you think?

**Comment by goanpeca** [comment]
Yes, that would be great!

**Comment by dpizetta** [comment]
I'll be working on qdark at night for those two weeks :)

**Comment by dpizetta** [comment]
Sorry again about it, working on this :) Tks

**Comment by dpizetta** [comment]
In the native Linux theme, ubuntu 18.04/gnome it does not provide an identifier for focus on tree and list views. I will try to use some similar to the table, it looks nice and it is quite similar we have been using for buttons. See some gif below:

![list-tree-view-in-linux-dark](https://user-images.githubusercontent.com/5084939/72371584-6ea4ed80-36e3-11ea-99ae-ca06f22f7bed.gif)

![list-tree-view-in-linux--nodark](https://user-images.githubusercontent.com/5084939/72371585-6ea4ed80-36e3-11ea-8478-f37e9208b2fe.gif)

**Comment by dpizetta** [comment]
@jnsebgosselin  in your image from using qdark the list/tree border do not light up when selected/hover? See my example below. Tks

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin in your image from using qdark the list/tree border do not light up when selected/hover? See my example below. Tks

Yes the list/tree border does highlight on mouse hover.

**Comment by dpizetta** [comment]
I want to change some things on those views, but they are not so easy to implement (actually, to understand and insert the right thing in the right place), so I will change this to the next version.

**Comment by dpizetta** [comment]
May @isabela-pf has a good idea of what color to use here. @juanis2112  @ccordoba12 thoughts?

Currently, it is like this:

![list-qdark](https://user-images.githubusercontent.com/5084939/112933475-50fc5200-90f6-11eb-937e-ee053bbc65bb.gif)

Maybe we can keep the same as the hovering one.

For comparison, an example of VSCode too.

![list-selection](https://user-images.githubusercontent.com/5084939/112933554-76895b80-90f6-11eb-9e44-c4133f4e5c58.gif)

**Comment by dpizetta** [comment]
The result is this
![table-views](https://user-images.githubusercontent.com/5084939/113224240-604bde80-9261-11eb-9f06-0278cd8e3ac6.gif)
