### ISSUE TITLE
QFrame does not style

### ISSUE THREAD

**Issue by wolfc01** [ColinDuquesnoy/QDarkStyleSheet#21]
Hello

if I have a QFrame having width=3 and height=3 pixels: it is visible. Otherwise not. IMHO this is wrong.

Best regards
Carl.

**Comment by ColinDuquesnoy** [comment]
The reason why we made it that way is explained in #17.

If you have a better solution feel free to submit a pull request.

**Comment by ColinDuquesnoy** [comment]
This might be due to #17. 

I don't have the time to work on that now but I'll accept and merge any pull request that fix the issue.

**Comment by ColinDuquesnoy** [comment]
Fixed in master branch. I will release a new version once #22 and #23 are fixed.

@wolfc01  Thank you very much for reporting!
