### ISSUE TITLE
Vertical QToolBar move handle uses horizontal image

### ISSUE THREAD

**Issue by dirkpitt2050** [ColinDuquesnoy/QDarkStyleSheet#210]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: Git master branch
- OS: all
- Python: all

### Language

All

### Description / Steps to Reproduce [if necessary]

[Description of the issue]

Vertical QToolBar move handle uses horizontal resource image. In qdarkstyle/qss/_styles.scss:

```
    &::handle {
       ...
        &:vertical {
            height: 16px;
            image: url($PATH_RESOURCES + '/rc/toolbar_move_horizontal.png');
        }
    }
```

### Actual Result

Vertical QToolBar handle uses horizontal image.

### Expected Results / Proposed Result

Vertical QToolBar handle should use toolbar_move_vertical.png

### Relevant Code [if necessary]

Just replace toolbar_move_horizontal.png above with toolbar_move_vertical.png

**Comment by goanpeca** [comment]
Thanks! we will fix this!
