### ISSUE TITLE
There is no style for focused or default button

### ISSUE THREAD

**Issue by jnsebgosselin** [ColinDuquesnoy/QDarkStyleSheet#211]
[Versions from your environment]

- QDarkStyle: commit 716979b7226949053ce387a89c034d933eba4bc8 on develop
- Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 
- Python: 3.7

There is actually no visual indicator for `focused` or `default` button in qdarkstyle. This makes navigating through the interface with the keyboard very hard because there is no way to know which button is focused and which is the default button.

Below I present an example comparing qdarkstyle with the Qt Windows vista style.

In the Qt windows vista style, the dark dashed frame indicates that the button is focused with the keyboard, while the solid blue frame indicates that it is the default button (meaning that a `clicked` signal is emitted if enter is pressed).

![qdarkstyle_focus](https://user-images.githubusercontent.com/10170372/69572464-31996600-0f92-11ea-82e0-474258d5a9fb.gif)

### Relevant Code [if necessary]

```python
import sys
import qdarkstyle
from qtpy.QtCore import Qt, Signal
from qtpy.QtWidgets import (QApplication, QPushButton,
                            QFrame, QGridLayout, QLabel)


app = QApplication(sys.argv)
app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())


class FocusEmittingButton(QPushButton):
    sig_focus_in = Signal(str)

    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        self.setFocusPolicy(Qt.StrongFocus)
        self.setAutoDefault(True)

    def focusInEvent(self, event):
        text = '{} is focused.'.format(self.text())
        self.sig_focus_in.emit(text)
        super().focusInEvent(event)


toolbar = QFrame()
layout = QGridLayout(toolbar)

label = QLabel('No button pressed.')
layout.addWidget(label, 0, 1, 1, 3)
for i in range(3):
    button = FocusEmittingButton('Button {}'.format(i + 1))
    button.sig_focus_in.connect(label.setText)
    layout.addWidget(button, 1, i + 1)
button.setFocus()

toolbar.show()
sys.exit(app.exec_())
```

**Comment by brezniczky** [comment]
Quite a problem - appears to also apply to Ubuntu 16.04.1, PySide2 5.14, Python 3.5.2.

**Comment by dpizetta** [comment]
Hi guys, I've changed to show border but less evident than when on focus. 

![focus](https://user-images.githubusercontent.com/5084939/72104560-798a0780-330a-11ea-8454-76d7d0b18a25.gif)

**Comment by goanpeca** [comment]
Thoughts @jnsebgosselin ?

**Comment by dpizetta** [comment]
In the buttons, the contrast is not so big because of the grey color, but I think it is ok. The gif also decrease the contrast when converted, it is a little higher live :)

Also, I changed the focus for other fields too, see below - I do not pull yet.

![focus-for-all-inputs](https://user-images.githubusercontent.com/5084939/72344774-d55ce380-36b0-11ea-9b07-d700976110f4.gif)
