### ISSUE TITLE
Impossible to change the color of the text of QTabBar with setTabTextColor

### ISSUE THREAD

**Issue by jnsebgosselin** [ColinDuquesnoy/QDarkStyleSheet#212]
[Versions from your environment]

- QDarkStyle: commit 716979b7226949053ce387a89c034d933eba4bc8 on develop
- Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 
- Python: 3.7

Setting the color of the text of individual tab in QTabBar with [QTabBar.setTabTextColor](https://doc.qt.io/qt-5/qtabbar.html#setTabTextColor) is not working when using qdarkstyle

Below I present an example that demonstrate the issue.

![image](https://user-images.githubusercontent.com/10170372/69827359-0bb7cf80-11e5-11ea-843e-91c18a1f2a47.png)

### Relevant Code [if necessary]

```python
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QApplication, QTabWidget, QWidget
import sys
import qdarkstyle

app = QApplication(sys.argv)
app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())

tabwidget = QTabWidget()
colors = ('red', 'green', 'black', 'blue')
for i, color in enumerate(colors):
    tabwidget.addTab(QWidget(), 'Tab #{}'.format(i + 1))
    tabwidget.tabBar().setTabTextColor(i, QColor(color))

tabwidget.show()
tabwidget.setMinimumWidth(300)
sys.exit(app.exec_())
```

**Comment by dpizetta** [comment]
Not sure how to provide this change. The tab widget does not accept QLabel, and HTML text is rendered colored as desired, but it stills with the HTML code be shown.

**Comment by goanpeca** [comment]
@dpizetta if we do not provide a color style for the whole tab widget text color this wotks, but as soon as we provide that color, then set tabcolor stops working with qdarkstyle.

One option would be to not enforce that color?

**Comment by dpizetta** [comment]
@goanpeca we can try that  :) Tks

**Comment by dpizetta** [comment]
> @dpizetta if we do not provide a color style for the whole tab widget text color this works, but as soon as we provide that color, then set tabcolor stops working with qdarkstyle.
> 
> One option would be to not enforce that color?

@goanpeca have you tried this? I do, but it stills having the problem. It would be inheriting. It does not work. I suggest @jnsebgosselin use icon if possible. If anyone has another idea, please let me know.

![Screenshot from 2020-01-16 15-44-43](https://user-images.githubusercontent.com/5084939/72553794-2ec33f00-3878-11ea-83ed-810bc4d9052c.png)

**Comment by goanpeca** [comment]
I remeber trying something along the lines I said and it worked but I would need to check again.

**Comment by dpizetta** [comment]
@jnsebgosselin now it should be working :)

**Comment by jnsebgosselin** [comment]
This is excellent, thank you very much!
