### ISSUE TITLE
Intermittent - Window objects become white from time to time

### ISSUE THREAD

**Issue by marcelomanzo** [ColinDuquesnoy/QDarkStyleSheet#213]
I'm using the following version:
https://github.com/ColinDuquesnoy/QDarkStyleSheet/archive/develop.zip

From time to time, my objects become white like this:
![image](https://user-images.githubusercontent.com/12878783/70375332-a04bbd00-18ca-11ea-95d9-439444a575e5.png)

Any idea what could be causing it, any command I could invoke to repaint?

Thanks!

**Comment by marcelomanzo** [comment]
Just for reference this is the normal state of the window:
![image](https://user-images.githubusercontent.com/12878783/70375356-f3257480-18ca-11ea-9223-5ffb882bcd46.png)

**Comment by dpizetta** [comment]
Hi, this is a real stranger problem. It seems a rendering problem, I recommend you to reinstall all qt things and python related to your project, and/or/ try your code in another machine with similar configuration. Another option is that in some moments of your code the stylesheet is reset then you set again the black theme or something is doing this reset, producing that weird behavior. Try to follow all calls for the setStyleSheet. I hope it helps! Tks

**Comment by dpizetta** [comment]
> Any idea what could be causing it, any command I could invoke to repaint?

Actually, no, and that is a problem to change the theme, we need to restart the application. So if you find how it does this, you can implement a new feature. :)

**Comment by dpizetta** [comment]
@marcelomanzo any new about this one? Does the problem persist? Tks

**Comment by dpizetta** [comment]
Closing due to no responses.
