### ISSUE TITLE
Drop down arrows randomly disappear in Dolphin

### ISSUE THREAD

**Issue by BParks21** [ColinDuquesnoy/QDarkStyleSheet#215]
![Screenshot (47)_LI](https://user-images.githubusercontent.com/12180630/73631234-6a0a8f80-4626-11ea-8813-fae40cd8caf0.jpg)
I've wanted to use this for the longest time but one minor bug prevents me from doing so. Whenever i enable this user style it works perfectly, at first. Then eventually at random all the drop down arrows will disappear in the gui. Look at the screenshot. They work initially but when i boot up my computer and use dolphin the next day they usually stop appearing.

**Comment by dpizetta** [comment]
Hi @BParks21 this was solved with the latest version of qdarkstyle? Ou anything else? We will appreciate your comments, tks

**Comment by BParks21** [comment]
@dpizetta  I forgot exactly how i solved this, but i remember it had to do with the image url's. I had to specify a very specific directory path for the icon locations in the .qss file. Because the default installation method worked, but only temporarily. Eventually the icons would disappear in dolphin.
![Screenshot (111)](https://user-images.githubusercontent.com/12180630/78957104-5c540900-7ab2-11ea-8ec8-a9a860752dba.png)
