### ISSUE TITLE
QGroupBox indicator size is incorrect

### ISSUE THREAD

**Issue by tsilia** [ColinDuquesnoy/QDarkStyleSheet#218]
- QDarkStyle: latest master
- OS: Windows 10
- Qt v5.12.2
Language: C++

When focused, QGroupBox's checkbox (indicator sub-element) is displayed in smaller size than any normal checkbox:
![qds_1_focused_groupbox](https://user-images.githubusercontent.com/60840213/75396532-c8fdb480-5905-11ea-93e2-688c84f5677e.png)

Expected Result:
The icon of the indicator sub-element of a QGroupBox should look the same way any normal checkbox does. This is how checkboxes look in default Win10 theme (dropdowns are related to another issue I'll file later):
![qds_4_default_win10_theme](https://user-images.githubusercontent.com/60840213/75396565-de72de80-5905-11ea-9383-ee1b136b756d.png)

**Comment by dpizetta** [comment]
Close in release v2.8.1 :) Tks for contributing!
