### ISSUE TITLE
QGroupBox's indicator displayed incorrectly when UNfocused

### ISSUE THREAD

**Issue by tsilia** [ColinDuquesnoy/QDarkStyleSheet#219]
Another issue with the QGroupBox's checkbox (indicator sub-element).

- QDarkStyle: latest master
- OS: Windows 10
- Qt v5.12.2
Language: C++

When focused, QGroupBox's checkbox (indicator sub-element) is displayed in smaller size than any normal checkbox:
![qds_2_unfocused_groupbox](https://user-images.githubusercontent.com/60840213/75396877-9d2efe80-5906-11ea-9537-815e9eb69143.png)
Looks like the style hasn't been applied to the sub-element.

Expected Result:
The icon of the indicator sub-element of a QGroupBox should look the same way any normal checkbox does.

**Comment by goanpeca** [comment]
Thanks for reporting @tsilia !

**Comment by dpizetta** [comment]
Close in release v2.8.1 :) Tks for contributing!
