### ISSUE TITLE
QDockWidget title bar on Mac OS X Yosemite

### ISSUE THREAD

**Issue by danarmstrong** [ColinDuquesnoy/QDarkStyleSheet#22]
I see that this is an issue that you have corrected in the past, however, using Qt 5.4 the QDockWidget title bar is not themed on Yosemite (probably not even related to Yosemite). The icons, however, are.

**Comment by ColinDuquesnoy** [comment]
Thanks for reporting those issues. I'll have a look ASAP

**Comment by ColinDuquesnoy** [comment]
Sorry but I cannot reproduce your issue on Yosemite with PyQt 5.4.1. Here is how it looks for me:
![screen shot 2015-04-22 at 17 08 29](https://cloud.githubusercontent.com/assets/1681217/7277844/87e20d10-e912-11e4-8113-ae35399d3d64.png)

Are you sure you're using the latest version? If yes could you provide me with an [SSCCE](http://sscce.org/) that reproduce the problem (preferably written in python)?

**Comment by danarmstrong** [comment]
I will try putting one together tonight when I'm back at the Mac. I am only using Qt with C++ so I will try both C++ and PyQt and see what my results are.

**Comment by danarmstrong** [comment]
I took a crash course in PyQt5 and discovered that the issue does not exist with the Python bindings, only when used with the C++ libs.

**Comment by danarmstrong** [comment]
You can find a bare minimum, compilable project demonstrating the problem here: https://www.dropbox.com/s/k343ankhzt6zu6e/darktest.zip?dl=0

**Comment by ColinDuquesnoy** [comment]
Thanks. I'll have a look ASAP.

**Comment by ColinDuquesnoy** [comment]
I forgot that the fix for issue #12 is not included in style.qss but applied conditionally at runtime when you load the stylesheet. The python package provides a function to load the stylesheet which takes care of that but, in C++ it's up to you to add the missing extra stylesheet. e.g:

```cpp
QString loadStyleSheet()
{
    QFile f(":qdarkstyle/style.qss");
    QString stylesheet;
    if (!f.exists()) {
        printf("Unable to set stylesheet, file not found\n");
    } else {
        f.open(QFile::ReadOnly | QFile::Text);
        QTextStream ts(&f);
        stylesheet = ts.readAll();
#ifdef Q_OS_MACX
        stylesheet += "QDockWidget::title"
        "{"
        "    background-color: #353434;"
        "    text-align: center;"
        "}";
#endif
    }
    return stylesheet;
}
```

**Comment by danarmstrong** [comment]
Everything looks fantastic now. Thank you for your responsiveness and prompt attention.

**Comment by ColinDuquesnoy** [comment]
Great. With the upcoming version 2.0, you will have to add the following line to QDockWidget::title stylesheet (I edited the original code).

```height: 12px;```
