### ISSUE TITLE
QDateTimeEdit with calendar popup displayed incorrectly

### ISSUE THREAD

**Issue by tsilia** [ColinDuquesnoy/QDarkStyleSheet#220]
- QDarkStyle: latest master
- OS: Windows 10
- Qt v5.12.2
Language: C++

DateTime with calendar popup has a dropdown arrow with a different look than ComboBox's arrow:
![qds_3_datetime_dropdown_inconsistency](https://user-images.githubusercontent.com/60840213/75397123-2e05da00-5907-11ea-9276-b9f7352baf2e.png)

Expected Result:
Dropdown arrow should look the same as in ComboBox. This is how they look in default Win10 theme:
![qds_4_default_win10_theme](https://user-images.githubusercontent.com/60840213/75396565-de72de80-5905-11ea-9383-ee1b136b756d.png)

**Comment by goanpeca** [comment]
Thanks for reporting @tsilia !

**Comment by dpizetta** [comment]
Close in release v2.8.1 :) Tks for contributing!
