### ISSUE TITLE
pyc files in PyPI package

### ISSUE THREAD

**Issue by sten0** [ColinDuquesnoy/QDarkStyleSheet#227]
Hi,

I'm packaging QDarkStyleSheet for Debian as a dependency of Vorta.  Our Python Team policy requires the use of tarballs from PyPI; however, unfortunately it seems the PyPI package for qdarkstyle contains bytecompiled files (not allowed by team policy), I'm guessing by accident.

### Description / Steps to Reproduce [if necessary]

1. curl https://files.pythonhosted.org/packages/38/91/2e90941a48e690ebd4d2e574417206d2d35a4e223c60878c76e7345f2dfb/QDarkStyle-2.8.tar.gz | tar xzf -
2. find QDarkStyle-2.8 | grep '\.pyc'

### Actual Result
```
QDarkStyle-2.8/qdarkstyle/__init__.pyc
QDarkStyle-2.8/qdarkstyle/__main__.pyc
QDarkStyle-2.8/qdarkstyle/pyqt_style_rc.pyc
```

### Expected Results / Proposed Result

No output, because no pyc files.  I hope a project maintainer will be willing to fix this soon so we can get QDarkStyleSheet into Debian :-)

Thank you,
Nicholas

**Comment by goanpeca** [comment]
@dpizetta could you take a look at this ;-)

**Comment by goanpeca** [comment]
@dpizetta we are now migrating some projects (eventually) all to use this tool for making releases

https://regro.github.io/rever-docs/

As part of those steps we can make sure to remove all unwanted files to avoid these problems in the future.

**Comment by dpizetta** [comment]
Perfect! I'll take a look this week! Tks

Em qui, 12 de mar de 2020 18:14, Gonzalo Peña-Castellanos <
notifications@github.com> escreveu:

**Comment by dpizetta** [comment]
Files removed in new version v2.8.1. AS @goanpeca  we will try to use tools like rever to make our building more robust, also I'm adding many tests in the travis/tox. Thanks for reporting.
