### ISSUE TITLE
Qdarkstylesheet can be loaded in QtDesigner?

### ISSUE THREAD

**Issue by bdeash** [ColinDuquesnoy/QDarkStyleSheet#234]
can be loaded from the same qt designer? im noob

**Comment by goanpeca** [comment]
Hi @pwnedbrian,

What do you mean?

**Comment by ZeldaZocker** [comment]
Sorry for hijacking this but it doesn't seems like @pwnedbrian saw that you responded. I think he is asking if the style can be used in the Qt Designer Application and if so how is it done? I'm asking this myself and if this isn't what he wanted to know i'm sorry.

**Comment by goanpeca** [comment]
I do not use qt designer so I am not sure.

@dpizetta do you happen to know 🙃?

**Comment by dpizetta** [comment]
Hi everybody, @ZeldaZocker and @pwnedbrian the answer is yes and no.  

What we can use with QtDesiner and other Qt resources is the QSS file (also QRC for images like icons), which we also generate in our structure. However,  the unique way it can be used is copying the text of QSS file into some setStyleSheet() content (see the example below). 

![qss-qt-desing](https://user-images.githubusercontent.com/5084939/83287786-a0ad7c80-a1b8-11ea-8d80-03c1eb16bcfa.gif)

It seems a feature that was not implemented yet, even many people asking. As it is just a style, people seem not to worry about it.

Related: https://www.qtcentre.org/threads/12454-how-to-apply-stylesheet-defined-in-qss-file-to-qt-application

**Comment by ZeldaZocker** [comment]
Thank you for the info. The workaround works but sadly there is some weird behavior like missing checkboxes (can also be seen in your gif) and tabs from a tabwidget which just stay white. So it's nice if you just want a quick preview of the dark style window but for creating a window i would stay with the default style.

**Comment by dpizetta** [comment]
@ZeldaZocker yes, but if you apply the stylesheet after you build the application, they appear.  As you said it works like a poorly preview. I always use the default style then apply the style sheet in the code, which is not practical for UI designers sadly. Tks
