### ISSUE TITLE
editing palette.py doesn't affect the theme

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [ColinDuquesnoy/QDarkStyleSheet#237]
# Describe Your Environment
```bash
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Windows
    - Release....................... 10
    - Platform...................... Windows-10-10.0.18362-SP0
    - Version....................... 10.0.18362
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.8.3
    - C Compiler.................... MSC v.1924 64 bit (AMD64)
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.8.3
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.15.0
    - PyQt5 Qt Version.............. 5.15.0
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.9.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.7.1
    - QDarkStyle.................... 2.8.1
```

### Language

Python

### Description / Steps to Reproduce [if necessary]

1. applying the theme as described in the [pyqt5 section](https://github.com/ColinDuquesnoy/QDarkStyleSheet#usage)
2. running the app and making sure that the theme is applied (works)
3. editing colors of qdarkstyle's palette.py in `%APPDATA%\Python\Python38\site-packages\qdarkstyle`
```python
class DarkPalette(object):
    """Theme variables."""

    # Color
    COLOR_BACKGROUND_LIGHT = '#505F69'
    COLOR_BACKGROUND_NORMAL = '#32414B'
    COLOR_BACKGROUND_DARK = '#19232D'
    
    # Edited to:
class DarkPalette(object):
    """Theme variables."""

    COLOR_BACKGROUND_LIGHT = '#f44336'
    COLOR_BACKGROUND_NORMAL = '#673ab7'
    COLOR_BACKGROUND_DARK = '#4caf50'

```
4. running again the app to check modification

### Actual Result

Nothing changed... new colors not applied

### Expected Results / Proposed Result

expected that the modification takes effect

so please how to change theme's color and apply our own palette... ?

**Comment by mIcHyAmRaNe** [comment]
i finally found how, 
i used the developer mode where i edited the `palette.py` file and then run `process_qrc.py` script which generated qss files :)

**Comment by dpizetta** [comment]
Hi @mIcHyAmRaNe sorry to make you find it by yourself. You are correct. The palette.py file you changed is the declaration of color variables that are used when we run the process_qrc.py. So, this generates the style.qss with the CSS and style.qrc with images and style_rc.py with the binary from both.  I need to add some more info about it in the CONTRIBUTING.rst. Tks
