### ISSUE TITLE
QComboBox cuts text

### ISSUE THREAD

**Issue by rimpy-custom** [ColinDuquesnoy/QDarkStyleSheet#239]
### Describe Your Environment

* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Windows
    - Release....................... 10
    - Platform...................... Windows-10-10.0.14393-SP0
    - Version....................... 10.0.14393
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.8.3
    - C Compiler.................... MSC v.1925 32 bit (Intel)
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.8.3
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.15.0
    - PyQt5 Qt Version.............. 5.15.0
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.9.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.7.1
    - QDarkStyle.................... 2.8.1

### Language

Python

### Description / Steps to Reproduce [if necessary]

If you set maximum horizontal size of QComboBox and add some text in it, you will notice that ~30 pixels of text are cut from right side.

### Actual Result

https://i.imgur.com/nVsZeFK.png

### Expected Results / Proposed Result

Text should be shown fully till the border. 
Issue do not exist in 2.7.0, probably because it has:
padding-right: 4px;
instead of 2.8.0 and 2.8.1:
padding-right: 36px;
set in style.qss for QComboBox. 

P. S. Not related to the issue, but spacing between checkboxes are too big. It is also on the image in comparison to standard windows style.

**Comment by rimpy-custom** [comment]
May sombody help me to fix that? I am not good enough to find out how I can change that in QDdarkStyle manually.

**Comment by rimpy-custom** [comment]
Have found a temporary solution, you may apply custom stylesheet:
myComboBox.setStyleSheet("QComboBox"
                                           "{"
                                           "padding-right: 4px;"
                                           "}")

**Comment by Jihadist** [comment]
Is this will be fixed in master?

**Comment by dpizetta** [comment]
We will release soon @Jihadist, thanks! Now is on the develop branch.
