### ISSUE TITLE
QSplitter handle not styled on OS X Yosemite

### ISSUE THREAD

**Issue by danarmstrong** [ColinDuquesnoy/QDarkStyleSheet#24]
Another issue discovered when using C++. The QSplitter handle isn't styled.

![screenshot 2015-04-25 01 37 35](https://cloud.githubusercontent.com/assets/4072243/7332089/bd082f3a-eaeb-11e4-8bb7-e1f3edcd469d.png)

**Comment by ColinDuquesnoy** [comment]
Fixed in master branch (this was not specific to c++)
