### ISSUE TITLE
Buttons size problems

### ISSUE THREAD

**Issue by RinnetenseiQ** [ColinDuquesnoy/QDarkStyleSheet#248]
I really like this library that sets up a dark theme for PyQt apps. However, I ran into some problem with the size of the widgets, in particular with the buttons. Screenshots are attached. This is bug? Can I fix it somehow? Please keep in mind that I am quite inexperienced in writing PyQt applications, and in Python in general.

[Versions from your environment]

- QDarkStyle:
- OS: Windows 10
- Python: 3.7

[If used, please inform their versions]
- PyQt: PyQt5==5.12.3

### Language
[Python]
![изображение_2020-11-29_231715](https://user-images.githubusercontent.com/49791012/100553830-05957c80-3299-11eb-8388-86d81e8204a5.png)

![image](https://user-images.githubusercontent.com/49791012/100553836-147c2f00-3299-11eb-9ec1-801b402b90e5.png)
![image](https://user-images.githubusercontent.com/49791012/100553840-1b0aa680-3299-11eb-934e-edc369d55080.png)

**Comment by dpizetta** [comment]
Hi @RinnetenseiQ  we are happy that you are using QDarkStyle. 

About the issue, what types of buttons you are using? You should use tool buttons for general ones. Push buttons have a minimum size set (like Ok, Cancel, Yes, etc).

This [link ]( https://stackoverflow.com/questions/38576380/difference-between-qpushbutton-and-qtoolbutton) can help you to decide.

**Comment by RinnetenseiQ** [comment]
> Hi @RinnetenseiQ we are happy that you are using QDarkStyle.
> 
> About the issue, what types of buttons you are using? You should use tool buttons for general ones. Push buttons have a minimum size set (like Ok, Cancel, Yes, etc).
> 
> This [link ](https://stackoverflow.com/questions/38576380/difference-between-qpushbutton-and-qtoolbutton) can help you to decide.

**Comment by RinnetenseiQ** [comment]
> Hi @RinnetenseiQ we are happy that you are using QDarkStyle.
> 
> About the issue, what types of buttons you are using? You should use tool buttons for general ones. Push buttons have a minimum size set (like Ok, Cancel, Yes, etc).
> 
> This [link ](https://stackoverflow.com/questions/38576380/difference-between-qpushbutton-and-qtoolbutton) can help you to decide.



> Hi @RinnetenseiQ we are happy that you are using QDarkStyle.
> 
> About the issue, what types of buttons you are using? You should use tool buttons for general ones. Push buttons have a minimum size set (like Ok, Cancel, Yes, etc).
> 
> This [link ](https://stackoverflow.com/questions/38576380/difference-between-qpushbutton-and-qtoolbutton) can help you to decide.

**Comment by RinnetenseiQ** [comment]
> Hi @RinnetenseiQ we are happy that you are using QDarkStyle.
> 
> About the issue, what types of buttons you are using? You should use tool buttons for general ones. Push buttons have a minimum size set (like Ok, Cancel, Yes, etc).
> 
> This [link ](https://stackoverflow.com/questions/38576380/difference-between-qpushbutton-and-qtoolbutton) can help you to decide.

**Comment by RinnetenseiQ** [comment]
> Hi @RinnetenseiQ we are happy that you are using QDarkStyle.
> 
> About the issue, what types of buttons you are using? You should use tool buttons for general ones. Push buttons have a minimum size set (like Ok, Cancel, Yes, etc).
> 
> This [link ](https://stackoverflow.com/questions/38576380/difference-between-qpushbutton-and-qtoolbutton) can help you to decide.

Thank for your answer. 
But the difference in button decoration between themes(Fusion, Windows vs QDarkStyle) is obvious from screenshots.
What is the reason for this deviation from the standard? Or did it happen by accident?

**Comment by dpizetta** [comment]
We want to apply the fixed size only for dialogs, fixed in the develop branch, tks.
