### ISSUE TITLE
hyperlinks are very hard to read

### ISSUE THREAD

**Issue by glevner** [ColinDuquesnoy/QDarkStyleSheet#250]
Hyperlinks in text are very hard to read (see attached image). I am not sure there is anything to be done about it, though, because Qt stylesheets don't seem to provide a way to specify link colors. Unless you make the background color a bit brighter...

![aboutqt](https://user-images.githubusercontent.com/2338018/102380283-0849de80-3fc8-11eb-9866-6d739e036732.png)

**Comment by dpizetta** [comment]
Hi, thanks for reporting this. However, we are not able to change hyperlinks in richtext/html which is not in the scope of the application stylesheet, see #112 at [here](https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/112#issuecomment-432906183).
