### ISSUE TITLE
QToolbar action with menu overlaps button text

### ISSUE THREAD

**Issue by stekow** [ColinDuquesnoy/QDarkStyleSheet#251]
If an action with a QMenu is placed inside a QToolbar, then the menu button texts or icon overlaps the menu arrow (see image).
Maybe someone has a solution?

Regards,

Piotr
### Describe Your Environment

- QDarkStyle: 2.8.1
- OS: Windows 10 64 Bit
- Python: 2.7.15 32 Bit
- PySide: 1.1.1

### Relevant Code 

```
import sys
import qdarkstyle
from PySide import QtGui

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyside())

    mw = QtGui.QMainWindow()
    toolBar = QtGui.QToolBar(mw)
    mw.addToolBar(toolBar)

    menu = QtGui.QMenu(mw)
    menu.addAction(QtGui.QAction(u'1', menu))
    menu.addAction(QtGui.QAction(u'2', menu))
    menu.addAction(QtGui.QAction(u'3', menu))

    ac = QtGui.QAction(u'Menu action', toolBar)
    ac.setMenu(menu)
    toolBar.addAction(ac)

    mw.show()
    app.exec_()
```
![qmenu issue](https://user-images.githubusercontent.com/51000086/102508192-6b4d7b00-4085-11eb-8ccb-f43ff29b6f27.jpg)

**Comment by stekow** [comment]
I found this quick and dirty solution:
```
w = toolBar.widgetForAction(ac)
w.setStyleSheet('QToolButton {padding-right:1.5em; }')
```

However, the problem exists in the style.

**Comment by dpizetta** [comment]
Hi @stekow could you check the last development version? May this was fixed. I added a menu inside the toolbar in our example, it seems to be working.

**Comment by stekow** [comment]
Hi @dpizetta with version 3.0.1 the issue is still there.

**Comment by dpizetta** [comment]
@stekow have you tested in a more recent version of python/pyside? We are not supporting Python2, pyqt4, pyside1.

**Comment by stekow** [comment]
> @stekow have you tested in a more recent version of python/pyside? 

No.

> We are not supporting Python2, pyqt4, pyside1.

"The most complete dark/light style sheet for Qt applications (Qt4, Qt5, **PySide**, PySide2, PyQt4, PyQt5, QtPy, PyQtGraph, Qt.Py)."

**Comment by dpizetta** [comment]
I understand. If possible, try to update your environment, it seems fixed with the new version. [Python 2 support ended in 2020](https://www.python.org/dev/peps/pep-0373/). 

![image](https://user-images.githubusercontent.com/5084939/113312224-751b8700-92e0-11eb-8832-1f24dcf2e7d3.png)

We forgot to update the description. Since we have many new versions, we have no condition to support all of them. Tks for noticing.
