### ISSUE TITLE
QComboBox, first selectable item takes too much space 

### ISSUE THREAD

**Issue by Regis111** [ColinDuquesnoy/QDarkStyleSheet#259]
Hello, I found bug with QComboBox. First selectable item on a popup list takes enormous amount of space. The problem is shown in the left gif. I'm using `PySide2 === 5.15.2`,  `QDarkStyle === 2.8.1`.
![with2](https://user-images.githubusercontent.com/44723806/107151768-a9b83580-6964-11eb-80a3-bd46953dad67.gif) ![without](https://user-images.githubusercontent.com/44723806/107151632-dddf2680-6963-11eb-886f-f21d38779cb8.gif) 

I know little about styling widgets in qt so if you could tell me how to override this setting, that would be a lot for me. Thank You!

**Comment by dpizetta** [comment]
Duplicate of #200. Could you please check if the current [develop branch](2dd3a9f2ebe52333987b476571c040d11bb67073) works for you?

**Comment by Regis111** [comment]
It does, thank you.
