### ISSUE TITLE
Greenish color - bug or feature ?

### ISSUE THREAD

**Issue by olivierdalang** [ColinDuquesnoy/QDarkStyleSheet#261]
### Describe Your Environment

- QDarkStyle: 2.8.1
- OS: Windows-10-10.0.19041-SP0
- Python: 3.9.1
- 
- PySide: 5.15.2
- PyQt: 5.15.2

### Language

Python

### Description / Steps to Reproduce 

After updating from version 2.3.1, everything looks very greenish. Not sure if this is a bug or a feature, as I see no mention of a color palette change in the changelogs, and screenshots from the docs are dead (so I can't compare).

1. Use QDarkStyle 2.3.1, it looks nice !
2. Use QDarkStyle 2.8.1 (or anything starting at 2.4), it looks green/blueish

### Actual Result

2.3.1
![image](https://user-images.githubusercontent.com/1894106/107833212-dfa94f80-6d92-11eb-88d4-392edd9c778a.png)

2.8.1
![image](https://user-images.githubusercontent.com/1894106/107833160-af61b100-6d92-11eb-9c6d-e93581e6aaf8.png)

### Expected Results / Proposed Result

Be able to continue using the less saturated color palette we had before.

Thanks for the great package !

**Comment by dpizetta** [comment]
@olivierdalang actually it is a feature, we have removed many colors (we had no palette) and restructured the palette between v2.4-2.8. But as in #252, #240 Spyder team is helping to provide a variety of theme colors. Soon it will be easy to choose your preferred color.
