### ISSUE TITLE
QComboBox: huge indentation of items when active (left margin) (develop branch)

### ISSUE THREAD

**Issue by SomberNight** [ColinDuquesnoy/QDarkStyleSheet#263]
### Describe Your Environment

```
$ qdarkstyle --all
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Linux
    - Release....................... 5.8.0-44-generic
    - Platform...................... Linux-5.8.0-44-generic-x86_64-with-glibc2.29
    - Version....................... #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.8.5
    - C Compiler.................... GCC 9.3.0
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.8.5
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.15.4
    - PyQt5 Qt Version.............. 5.15.2
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.9.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.7.1
    - QDarkStyle.................... 3.0.dev0
```
```
~/wspace/QDarkStyleSheet$ git log -n 1
commit b72fc25ba40ff1b57af416c30022c1d5477d3a5c (HEAD -> develop, origin/develop)
Author: Daniel Pizetta <daniel.pizetta@usp.br>
Date:   Sat Mar 13 01:48:25 2021 -0300
```

### Language

Python

### Description / Steps to Reproduce [if necessary]

On latest develop HEAD, all ComboBoxes started to indent items when the ComboBox is active, which results in the labels getting cropped (not being fully visible). This behaviour was not there in 2.8.1.

![active](https://user-images.githubusercontent.com/29142493/111029320-04c1ca00-83f4-11eb-84b7-9165ac6ceb86.PNG)
![inactive](https://user-images.githubusercontent.com/29142493/111029327-0db29b80-83f4-11eb-9f1e-95f44215b7aa.PNG)

**Comment by dpizetta** [comment]
@SomberNight thanks for noticing this. Please check if the latest 'develop' version could solve this - we reduced the padding for the combo box items. Tks

**Comment by dpizetta** [comment]
Oh, if it is possible try to give us feedback about Qt version (try to use 5.12 also) if you have time.

**Comment by SomberNight** [comment]
I've now tested `QDarkStyle==3.0.2` and the issue seems to be fixed.

Tested on the same Linux/Ubuntu system with both `(Qt==5.15.2, PyQt==5.15.4)` and `(Qt==5.12.8, PyQt==5.14.1)`;
and also tested on Win10 with `PyQt==5.15.4`.

**Comment by lingchingteng** [comment]
I still have this issue with (Qt==5.15.2, PyQt==5.15.4)
