### ISSUE TITLE
Change hover color for menus

### ISSUE THREAD

**Issue by juanis2112** [ColinDuquesnoy/QDarkStyleSheet#266]
Color for hover in menus doesn't have enough contrast with background color.
<img width="271" alt="Screenshot 2021-03-16 at 9 08 23 PM" src="https://user-images.githubusercontent.com/18587879/111403862-c2221b00-869b-11eb-906d-68c4061406d5.png">

**Comment by dpizetta** [comment]
Fixed with 5938cf4b67b6e0661819bfed4193ef7366592bbe
