### ISSUE TITLE
Match size/behavior of close/float buttons in docks and tabs

### ISSUE THREAD

**Issue by juanis2112** [ColinDuquesnoy/QDarkStyleSheet#267]
The idea is to match the size of these two buttons, to the size of the x in the tabs

**Comment by dpizetta** [comment]
Current size on Windows. Note docks and tabs.

![image](https://user-images.githubusercontent.com/5084939/112245943-a933df80-8c30-11eb-8e62-f052916f9d09.png)

**Comment by dpizetta** [comment]
@juanis2112 please add a similar screenshot from mac in order to compare, please :)

**Comment by juanis2112** [comment]
Here is the screenshot for Mac:
<img width="1338" alt="Screenshot 2021-03-24 at 10 10 37 AM" src="https://user-images.githubusercontent.com/18587879/112334126-3145d380-8c89-11eb-85ce-3898042622ed.png">

**Comment by juanis2112** [comment]
Here is the screenshot for Linux:
![imagen (3)](https://user-images.githubusercontent.com/18587879/112348924-483ef280-8c96-11eb-9291-1e523b85744d.png)

**Comment by dpizetta** [comment]
**X SIZE IN TABS FOR WINDOWS/LINUX**

Original
 
![image](https://user-images.githubusercontent.com/5084939/112354326-577c6b00-8cab-11eb-8d8a-508392a6fa19.png)

Adjusting padding (1px to 3px) to correct X in tabs for Windows/Linux. 

![image](https://user-images.githubusercontent.com/5084939/112354388-66fbb400-8cab-11eb-9a4c-c1f493d64e0d.png)

**DOCK BUTTONS**

I needed to change the construction, so now they have the same behavior of tab buttons, so it maybe affects the size in mac, please confirm those for me.

![image](https://user-images.githubusercontent.com/5084939/112354480-7ed33800-8cab-11eb-9c6e-10513a04f1ac.png)
![dock-buttons](https://user-images.githubusercontent.com/5084939/112354506-84c91900-8cab-11eb-85d9-eeb65497f28a.gif)

**Comment by dpizetta** [comment]
I need to change the default color in light theme for the dock buttons:

![image](https://user-images.githubusercontent.com/5084939/112364476-53554b00-8cb5-11eb-8459-79bb2006541d.png)

**Comment by juanis2112** [comment]
This is how it is looking for me now in the current develop branch
<img width="331" alt="Screenshot 2021-03-25 at 3 59 47 PM" src="https://user-images.githubusercontent.com/18587879/112543058-456dfb80-8d83-11eb-8255-46671fb07c80.png">
<img width="611" alt="Screenshot 2021-03-25 at 4 01 26 PM" src="https://user-images.githubusercontent.com/18587879/112543131-5c145280-8d83-11eb-87fd-b451ae23a2f5.png">
