### ISSUE TITLE
Improvements and fixes  for v3.0 release

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#269]
@juanis2112 please add screenshots with all screens of qdarkstyle example, so I can compare 'ios' version with linux/windows to properly apply the fixes for X in dock and tabs, and undock button in docks. Tks

Writing the main points of our meeting/issues that I'll implement:

- [x] Disconnect tree/list selection/hover color with editor selection color, also check the colors;
- [x] Match/connect pressed menu color with hover/pressed color in the menu (submenus), also check the colors;
- [x] Match Undock/Close buttons in docks and tabs (OS-dependent) #267;
- [x] Hover color for indicators (checkbox/radio) in menus (check on Spyder hamburger menu) may be related to the previous item;
- [x] Fix padding for menus with indicators/icons (Qt version dependent) #214;
- [x] Update main.scss to make the proper descriptions of the new colors;
- [x] Check/update docs based on the new palette system;
- [x] Check over Windows/Linux/Mac and Qt versions 5.12, 5.13, 5.14, 5.15 ( menus with indicators/combo boxes/close-float buttons);

_Originally posted by @dpizetta in https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/262#issuecomment-805378798_

**Comment by juanis2112** [comment]
Screenshots for Mac:
<img width="1440" alt="Screenshot 2021-03-25 at 3 50 23 PM" src="https://user-images.githubusercontent.com/18587879/112541872-e8be1100-8d81-11eb-9143-32983d9f893b.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 50 20 PM" src="https://user-images.githubusercontent.com/18587879/112541887-ecea2e80-8d81-11eb-85f9-e7ed93477bfc.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 50 18 PM" src="https://user-images.githubusercontent.com/18587879/112541893-ee1b5b80-8d81-11eb-80b4-f81b9032c5f1.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 50 13 PM" src="https://user-images.githubusercontent.com/18587879/112541896-ef4c8880-8d81-11eb-9bfa-a2a2e7a27c41.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 50 03 PM" src="https://user-images.githubusercontent.com/18587879/112541902-efe51f00-8d81-11eb-893f-7c5e95c9b35b.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 49 48 PM" src="https://user-images.githubusercontent.com/18587879/112541906-f07db580-8d81-11eb-9158-83363d1e03c6.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 49 40 PM" src="https://user-images.githubusercontent.com/18587879/112541907-f1164c00-8d81-11eb-9660-45d9f947e000.png">
<img width="1440" alt="Screenshot 2021-03-25 at 3 49 18 PM" src="https://user-images.githubusercontent.com/18587879/112541908-f1aee280-8d81-11eb-8f4c-b007623bc1c0.png">

**Comment by dpizetta** [comment]
@ccordoba12 @juanis2112 there is a pre-release version in PyPI (`pip install QDarkStyle==3.0rc0`). I'm going to work on the last details and issues related to Qt versions. Tks

**Comment by ccordoba12** [comment]
Thanks a lot for your help @dpizetta! We're testing it right now (see https://github.com/spyder-ide/spyder/pull/15048), but things seem to be working fine locally.

We'll have more news for you tomorrow when @juanis2112 add the light theme to Spyder.
