### ISSUE TITLE
Improve selected tab background color and title contrast

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#270]
What do you think @juanis2112, @ccordoba12 and @isabela-pf.

Original

![image](https://user-images.githubusercontent.com/5084939/112354951-f4d79f00-8cab-11eb-9447-f40bb5047d58.png)

Changing the background color of the selected tab (tab bar), **using background 4** (the same as non selected, original is background 6). Note the title contrast when the background is darker. For me, the blue bar is sufficient to point to the selected one. 

![image](https://user-images.githubusercontent.com/5084939/112355005-00c36100-8cac-11eb-918e-22b7100e5f47.png)

Changing the background color of the selected tab (tab bar), **using background 5** (lighter than non-selected, original is background 6). Yet I prefer the same background to enhance the title contrast.

![image](https://user-images.githubusercontent.com/5084939/112355510-7cbda900-8cac-11eb-8895-6382c25b1901.png)

**Comment by ccordoba12** [comment]
> Changing the background color of the selected tab (tab bar), using background 5 (lighter than non-selected, original is background 6). Yet I prefer the same background to enhance the title contrast.

I know this is quite subjective, but I really prefer to have a lighter color for selected tabs. However, if we could adjust that on Spyder.

**Comment by dpizetta** [comment]
The current one, same colors, light theme:

![image](https://user-images.githubusercontent.com/5084939/112363900-c611f680-8cb4-11eb-8460-0af22265e213.png)

**Comment by juanis2112** [comment]
I agree with Carlos. I think it looks better with different colors between the tabs but we can implement that easily only for Spyder if you want to change it @dpizetta

**Comment by dpizetta** [comment]
I've set a mid-tone (the original was 6, identical was 4), now it is 5. Tks guys
