### ISSUE TITLE
C++ interchange of dark/light themes

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#273]
I'm not sure if I should open a new issue or not, but I'll do it if I'm said to.

I've tried to add the new light style to [DB Browser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser). I want to provide three options: follow the desktop style, dark style and light style. I cannot add these two options with qdarkstyle at the same time. My impression is that the Qt or cmake generation for the resources are overlapped due to usage of the same file name for both savours.  This is what I've changed in [CMakeLists.tst]( https://github.com/sqlitebrowser/sqlitebrowser/blob/c5199f559d2e734075af85faed2a00ed334cdcd0/CMakeLists.txt#L277) to include both styles:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 91573df6..22b1dbca 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -274,7 +274,8 @@ set(SQLB_RESOURCES
        src/translations/flags/flags.qrc
        src/translations/translations.qrc
        src/certs/CaCerts.qrc
-       src/qdarkstyle/style.qrc
+       src/qdarkstyle/light/style.qrc
+       src/qdarkstyle/dark/style.qrc
 )
 
 set(SQLB_MISC
```

Only the last listed `qrc` can be used, probably because this file is generated twice: `qrc_style.cpp`

Which is the recommended way to include both? The instructions in the README have not been updated, by the way.

_Originally posted by @mgrojo in https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/240#issuecomment-809600102_

I've worked around this problem renaming `style.qrc` to `lightstyle.qrc` and `darkstyle.qrc` accordingly. Please, let me know if there is a better way to do this, specially for not needing to change QDarkStyleSheet as provided.

_Originally posted by @mgrojo in https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/240#issuecomment-810551163_

**Comment by dpizetta** [comment]
@mgrojo thanks for testing that soon. I opened a new issue regarding specific this problem. I'll take some time to get a better answer to you since I mainly use Python version of it. 

The problem is like you said that the file is being overwritten, may we need to find a way to create the resulting file in different places, so we can keep the names. Or doing something like you did, with different file names. I'll search for options when compiling, if you have other ideas, please, let us know.

**Comment by mgrojo** [comment]
Thanks for looking into this, and for the new style, by the way!

**Comment by Jihadist** [comment]
When it will be in upstream? Looks like it's an old problem

**Comment by dpizetta** [comment]
@mgrojo Maybe we can "duplicate" the file using two different names for them or a way to include the whole path that does not overwrite the theme files when importing them. 

This seems a flat reference:

```
	src/qdarkstyle/style.qrc
        src/qdarkstyle/darkstyle.qrc  /*only points/imports to the /dark/darkstyle.qrc*/
        src/qdarkstyle/lightstyle.qrc  /*only points/imports to the /light/lightstyle.qrc*/
	src/qdarkstyle/dark/style.qrc
	src/qdarkstyle/light/style.qrc
```

or, closer to your solution

```
	src/qdarkstyle/style.qrc
        src/qdarkstyle/dark/darkstyle.qrc  /*only points/imports to the darkstyle.qrc*/
	src/qdarkstyle/dark/style.qrc
        src/qdarkstyle/light/lightstyle.qrc  /*only points/imports to the lightstyle.qrc*/
	src/qdarkstyle/light/style.qrc
```

@mgrojo, if you had some time, could you please check these solutions? I have no C++ environments at this moment.

**Comment by dpizetta** [comment]
@Jihadist if you could test for us would be great and we can include it soon. Feel free to open MR if you like. Tks

**Comment by mgrojo** [comment]
Sorry for answering so late, I was pretty busy lately.

I tested the changes by @Jihadist and I had to make an additional change to fix references to `style.qss`. After that change, it worked fine. I've made a new pull request with that fix.

**Comment by dpizetta** [comment]
It should be fixed with your contributions! Let us know if you have any other problems. Tks
