### ISSUE TITLE
Example to load light theme in README file

### ISSUE THREAD

**Issue by wxguy** [ColinDuquesnoy/QDarkStyleSheet#284]
I would like to use light and dark theme from `qtdarkstylesheet` package. However, there is no guide or reference I could find. How do we use the light theme from `qtdarkstylesheet`.

**Comment by wxguy** [comment]
Also to add up, the `app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api='pyqt5', palette='light'))` which is supported as per source code is not supported for `PyQt5`. It shows following error:-

```
File "C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\site-packages\qdarkstyle\__init__.py", line 322, in load_stylesheet
    raise TypeError("load_stylesheet() takes only zero or one argument: "
TypeError: load_stylesheet() takes only zero or one argument: (new) string type qt_api='pyqt5' or (old) boolean type pyside='False'.
```

**Comment by shaund** [comment]
Using `app.setStyleSheet(qdarkstyle.load_stylesheet(palette=qdarkstyle.LightPalette))` should work.

**Comment by wxguy** [comment]
Well. It appears that what I installed was version 2.x whereas the latest version published was 3.x. So I could get the intended result of documentation. Fixed it with upgrading the module to latest version.
