### ISSUE TITLE
radio_indeterminate style should be removed

### ISSUE THREAD

**Issue by PlasmaMichael** [ColinDuquesnoy/QDarkStyleSheet#29]
radio_indeterminate.png is missing

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting. I'll have a look but it is not likely to be fixed before a few weeks (I am pretty busy with other projects).

**Comment by DreamMichael** [comment]
It sounds not correct to have indeterminate state for QRadioButton, at the end the only fix on this issue is to remove the indeterminate style.

**Comment by ColinDuquesnoy** [comment]
Indeed, it should be removed. PR?

**Comment by DreamMichael** [comment]
Removed I think since it's not correct.

**Comment by ColinDuquesnoy** [comment]
Removed.
