### ISSUE TITLE
External "link" buttons display in default blue

### ISSUE THREAD

**Issue by DannyyyOnGit** [ColinDuquesnoy/QDarkStyleSheet#294]
### Describe Your Environment

[Dolphin Emulator](https://dolphin-emu.org/) end user. Theme properly edited to support the custom themes feature. No custom compile or anything similar. Directly downloaded [from here](https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/qdarkstyle/dark) and changed some qss file paths for Dolphin.

The issue I'm experiencing is that external "hyperlink" buttons don't seem to have any property, in order to define their color. Basically leaving them default blue, which doesn't go well with the theme in general. I'm not sure if this is an issue with Dolphin not reading an existing definition properly or this type of button not having any definitions at all. 

### Info
- Qt 5.15.0
- OS: Windows 10
- Dolphin: 5.0-15236
- Theme Download: https://drive.google.com/file/d/1OomXlzRtdH2YEXEH83z6_iI2v9HgffEi/view

### Description / Steps to Reproduce

1. Put "QDarkStyleSheet" folder into source folder (where _dolphin.exe_ is)
2. Put "QDarkStyleSheet.qss" into C:\Users\YOURNAMEHERE\Documents\Dolphin Emulator\Styles
3. Open Dolphin Config > Interface and check "Use Custom User Style" (app restart might be required)
4. Select "QDarkStyleSheet" user style with optional general theme color
5. Open "About" under "Help" menu

### Actual Result
External links have a blue color, which doesn't go well with the theme's background color.

**Screenshot:**
![image](https://user-images.githubusercontent.com/86955470/134388819-f42548f4-da6a-4d78-b082-209842c986a5.png)

### Expected Results / Proposed Result
Shouldn't be blue and fit with the rest of the theme (perhaps grey).

**Comment by ccordoba12** [comment]
Hey @DannyyyOnGit, thanks for reporting. You said

> Dolphin Emulator end user

Is that a C++ or Python app?

**Comment by DannyyyOnGit** [comment]
Here is the about dialog. From the looks of it, Dolphin uses simple hyperlinks.
https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/DolphinQt/AboutDialog.cpp

I guess my question would be, how an override/styling for that would look like?
Any help is appreciated. Might also be worth to maybe include the defintion in here as well.

**Comment by DannyyyOnGit** [comment]
After some more research. This seems to be caused by a Qt limitation: https://stackoverflow.com/questions/13416183/qt-stylesheet-how-to-set-color-of-qpalettelink-and-qplattelinkvisited

I've talked with the Dolphin app developers and they might add a workaround for this in the future.
Closing since this is an external issue.
