### ISSUE TITLE
test_create_qss fails

### ISSUE THREAD

**Issue by juliangilbey** [ColinDuquesnoy/QDarkStyleSheet#297]
The test function `test_create_qss` fails: it calls `create_qss()` with no arguments, but `qdarkstyle/utils/scss.py` reads:
https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/cbc93c0552645218650f280a1d2179617ba58cd2/qdarkstyle/utils/scss.py#L109-L115
so it fails.

**Comment by dpizetta** [comment]
Fixed in 9e72c253b0f6d80b2a70f24c26de93b29461b16e, thanks!
