### ISSUE TITLE
Non-py files not included by setup.py install

### ISSUE THREAD

**Issue by juliangilbey** [ColinDuquesnoy/QDarkStyleSheet#299]
`setup.py` includes the line:
```python
    include_package_data=True,  # add data file from MANIFEST.in #193
```
to include the data files in the package wheel.  But this only works for `bdist` and `sdist`. It is necessary to also have a `package_data=...` option to include it when running `setup.py install`; see https://setuptools.pypa.io/en/latest/userguide/datafiles.html

**Comment by ccordoba12** [comment]
@juliangilbey, you're welcome to submit a PR for this. Thanks!

**Comment by juliangilbey** [comment]
@ccordoba12 Done!

**Comment by ccordoba12** [comment]
Thanks! I'll let @dpizetta to review it.
