### ISSUE TITLE
QCheckbox hover

### ISSUE THREAD

**Issue by PlasmaMichael** [ColinDuquesnoy/QDarkStyleSheet#30]
Since QCheckBox uses png files, it misses of color on hover, surely the same for QRadioButton.

**Comment by ColinDuquesnoy** [comment]
Yes hover is missing for both QCheckBox and QRadioButton.

**Comment by DreamMichael** [comment]
I tried to add a hover png but when the checkbox is focus the hover is never showed when the mouse is on the widget, without the use of png for the border (old stylesheet) this issue is not there.

**Comment by ColinDuquesnoy** [comment]
Hover will now use the same color as focus.
