### ISSUE TITLE
Combobox contain empty icon area

### ISSUE THREAD

**Issue by SpiritBlossomAhri** [ColinDuquesnoy/QDarkStyleSheet#311]
<img width="174" alt="스크린샷 2022-03-24 01 53 45" src="https://user-images.githubusercontent.com/74236661/159753615-735e6206-a6c8-4523-92dc-67fe22d1ded3.png">

Is there anyone resolve this problem? combobox contain empty image line. how to fix it?

**Comment by glevner** [comment]
We have the same problem on Linux (but not on Windows). Were you able to find a solution?

**Comment by glevner** [comment]
This would seem to be a duplicate of issue #308, by the way.

**Comment by ccordoba12** [comment]
You're right. Closing this one then.
