### ISSUE TITLE
djef

### ISSUE THREAD

**Issue by panqinglong-0** [ColinDuquesnoy/QDarkStyleSheet#317]
### Describe Your Environment

Please, report the output of the command (from v2.6+) or fill the information below:

`$ qdarkstyle --all`

Or use the helpdev if you have

`$ helpdev`

[Versions from your environment]

- QDarkStyle:
- OS:
- Python:

[If used, please inform their versions]

- PySide:
- PyQt:
- PyQtGraph:
- QtPy:
- QT_API:
- PYQTGRAPH_QT_LIB:

### Language

[Python] or [C++]

### Description / Steps to Reproduce [if necessary]

[Description of the issue]

1. [First Step]
2. [Second Step]
3. [and so on...]

### Actual Result

[A description, output ou image of the actual result]

### Expected Results / Proposed Result

[A description, output ou image of the expected/proposed result]

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```
# code here to reproduce the problem
```

**Comment by panqinglong-0** [comment]
djndrn

**Comment by panqinglong-0** [comment]
6

**Comment by ccordoba12** [comment]
Closing because this is empty.
