### ISSUE TITLE
QRadioButton indicator issue

### ISSUE THREAD

**Issue by PlasmaMichael** [ColinDuquesnoy/QDarkStyleSheet#32]
I think it's an error:
QRadioButton::indicato::menu-arrowr:checked:pressed
Should be:
QRadioButton::indicator:checked:pressed

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting. It would be nice if you could submit PR to fix that (and maybe other similar issues). That way a fix would be released quicker than if you wait for me to look into the issue.

**Comment by DreamMichael** [comment]
I've fixed on my side but I don't use 100% the same stylesheet and I have custom style inside it because of the application i'm working on.

**Comment by ColinDuquesnoy** [comment]
I see. Ok no problem, other user will just have to wait for me to fix the issue, unless someone else want to fix it.

Anyway, thank you for your contribution!
