### ISSUE TITLE
Improve C++ use case explanation in  documentation

### ISSUE THREAD

**Issue by AlexPoltak** [ColinDuquesnoy/QDarkStyleSheet#329]
Hi.I would like to use QDarkStyleSheet in my application. I code in c++ and in README is wrote that i should copy files :
qdarkstyle/theme/style.qss
qdarkstyle/theme/style.qrc
qdarkstyle/theme/rc/ (the whole directory)

However the folder "theme" i could not find on branch. 
How can i implement this dark theme to my c++ qt app? 
Really thanks for reply.

**Comment by Jihadist** [comment]
hi, you need another folder https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/qdarkstyle/dark

**Comment by dpizetta** [comment]
@AlexPoltak [theme] should be changed to the theme chosen, for example: qdarkstyle/dark/darkstyle.qss. We will try to improve the description.
