### ISSUE TITLE
Custom style of specific widget 

### ISSUE THREAD

**Issue by Luyaojun** [ColinDuquesnoy/QDarkStyleSheet#330]
## Environment
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Windows
    - Release....................... 10
    - Platform...................... Windows-10-10.0.19041-SP0
    - Version....................... 10.0.19041
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.6.4
    - C Compiler.................... MSC v.1900 64 bit (AMD64)
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.6.4
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.15.4
    - PyQt5 Qt Version.............. 5.15.2
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 2.0.1
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.7.1
    - QDarkStyle.................... 3.1

[Description of the issue]
I have some sprcific widgets with another style. And it will be disabled.
For example:
```
self.table_view = QTableView(self)
self.table_view.setStyleSheet(
    '''
    QTableView{
        border: 1px solid rgb(45, 45, 45);
        gridline-color: rgb(60, 60, 60);
        background-color: red;
        selection-background-color: green;
    }
    '''
)
```
Without using QDarkStyleSheet, the cell item will be green when it is selected. And After invoking `app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())` , the item will be a dark style.
Is there any suggestions to solve the problem? Thank you~

**Comment by dpizetta** [comment]
@Luyaojun thanks for the contact. You can append the patch you made in the end of the stylesheet provided by qdarkstyle. Something like this:

mypatch = '''
    QTableView{
        border: 1px solid rgb(45, 45, 45);
        gridline-color: rgb(60, 60, 60);
        background-color: red;
        selection-background-color: green;
    }
    '''

style = qdarkstyle.load_stylesheet_pyqt5()
app.setStyleSheet(style + mypatch)

You also avoid using style changes over the code and have everything in one place. If you want this change on a specific object, you can use the css properties to do that. I hope this works for you.

**Comment by Luyaojun** [comment]
Thanks for your reply!

**Comment by Luyaojun** [comment]
Sorry to bother you again.
Is it possible to modify its style dynamically？
I need to change the background color of selected items according to their data.
It seems that no ItemDataRole matches the selected situation?

**Comment by Luyaojun** [comment]
I tried the code below:
```
app = QApplication.instance()
dark_style_sheet = qdarkstyle.load_stylesheet_pyqt5()
dynamic_style = '''
    QTableView#tableView_task::item:selected{
        background: red;
        color: white;
    }
'''
app.setStyleSheet(dark_style_sheet + dynamic_style)
```
It works fine, but may be not elegant.
Appreciate for any suggestions in advance!
