### ISSUE TITLE
Release 3.2

### ISSUE THREAD

**Issue by ccordoba12** [ColinDuquesnoy/QDarkStyleSheet#336]
@dpizetta, everything is ready for 3.2, so we'd really appreciate your help to release it given that you know quite well the process to do it.

Thanks!

**Comment by dpizetta** [comment]
Done :) https://pypi.org/project/QDarkStyle/

**Comment by ccordoba12** [comment]
Thanks @dpizetta!

**Comment by musicinmybrain** [comment]
Could someone please push the `v3.2` tag to this repository? Thanks!

**Comment by Ancieg** [comment]
Please add `v3.2` tag to the repository.
