### ISSUE TITLE
QToolButton:checked/pressed issue

### ISSUE THREAD

**Issue by goditsa8** [ColinDuquesnoy/QDarkStyleSheet#35]
Ubuntu 14.04, Unity shell.
In checked/pressed state QToolButton gets a little bigger that cause QToolBar gets bigger.
Adding `padding: 2px;` to `QToolButton:hover, QToolButton::menu-button:hover` and `QToolButton:checked, QToolButton:pressed, QToolButton::menu-button:pressed` helps me.
Sorry for my English.

**Comment by ColinDuquesnoy** [comment]
Thank you for the hint! This is fixed in latest commit on master branch.
