### ISSUE TITLE
QToolBar "expand" button unstyled

### ISSUE THREAD

**Issue by JSandusky** [ColinDuquesnoy/QDarkStyleSheet#37]
When a QToolBar is sized such that not all items appear the button to open the window containing the hidden items is lacking any styling.

Appears to just inherit QToolBar QToolButton's styling, probably needs arrow icons. Will send p/r to fix if I track down where that is styled.

**Comment by ColinDuquesnoy** [comment]
Maybe this can be done by styling the [::scroller](http://doc.qt.io/qt-5/stylesheet-reference.html#scroller-sub) sub-control?

**Comment by JSandusky** [comment]
So far it's been looking like the "extend" button isn't exposed to QSS, while hunting it down I've come across quite a few subjects similar to this http://stackoverflow.com/questions/27040897/qt-style-the-arrow-when-a-qtoolbar-is-too-small Unfortunately all  of them have had similarly old dates.

I haven't given the workaround presented there a shot yet though, hopefully when I get giving that a whirl I'll notice that there's some widget properties that could be used for property dependent selectors or something other than using coded styles.

**Comment by ColinDuquesnoy** [comment]
Maybe have a look at PR #40, it looks like the user found a fix for the expand button of vertical toolbars (I haven't had the time to review it).

**Comment by JSandusky** [comment]
Yes, that's the same thing. The coloring for the button is certainly acceptable as a stand in.

I've been having considerable trouble finding traits that avoid aliasing in the bitmap resources.

I think I can mark this mostly closed as PR #40 is "good enough and sufficiently clear" in it's changes to the extension button, and a "desired" solution looks impractical.
