### ISSUE TITLE
Can QColorDialog be styled?

### ISSUE THREAD

**Issue by leplatrem** [ColinDuquesnoy/QDarkStyleSheet#39]
It seems impossible since it comes from desktop... the only solution available is to reimplement a custom one?

Thanks for this awesome theme!

**Comment by ColinDuquesnoy** [comment]
Yes, I think you're right. The same restriction applies for all native dialogs (QFileDialog, QColorDialog,...).

**Comment by ntjess** [comment]
For reference, this appears to be implemented now:
![image](https://user-images.githubusercontent.com/23620506/79826973-1bd67400-836b-11ea-96d7-3835bc644cc2.png)
