### ISSUE TITLE
QList - setAlternatingRowColors

### ISSUE THREAD

**Issue by PKEv** [ColinDuquesnoy/QDarkStyleSheet#41]
not supported

**Comment by ColinDuquesnoy** [comment]
Thanks for reported. Unfortunately I don't have much time to work on the stylesheet. A PR would be very much appreciated.

**Comment by PKEv** [comment]
I was wrong.
error in something else ...
when you try to use a style that's for this application: https://github.com/QTodoTxt/QTodoTxt
inherited style of QWidget is using for QListWidget 
We will try to continue

**Comment by PKEv** [comment]
help only setup style for QDialog and QMainWindow instead QWidget

**Comment by ColinDuquesnoy** [comment]
> inherited style of QWidget is using for QListWidget 
help only setup style for QDialog and QMainWindow instead QWidget

Sorry I have no clue about what you mean.

**Comment by PKEv** [comment]
The problem was a bit different.
In this project uses components: QListWidget
In this component, the background elements can not setup when you set the background Qwidget
and therefore I had to give up the job of the parent parameters and set parameters for the background of all used children: QMainWindow, QDialog

**Comment by ColinDuquesnoy** [comment]
I think the case of custom widgets in QListWidget should be handled by application maintainers and not in this stylesheet. Therefore I am going to close this issue. Comment if you think there is something we could do in the stylesheet to address your issue.
