### ISSUE TITLE
Cannot set QDialog border style in css

### ISSUE THREAD

**Issue by ningquec** [ColinDuquesnoy/QDarkStyleSheet#45]
Hi,
    This style sheet is awesome, but when I use it, I can't set qdialog border in your .css. 
    I created a dialog as my main window, and setWindowFlags(Qt::FramelessWindowHint) for it , then added
```
QDialog #MyDialog
{
    border: 1px solid white;
}
```
   but it did't work. I don't know why.

**Comment by ColinDuquesnoy** [comment]
This does not work because window decorations (border, title bar, ...) are rendered by the window manager of your OS, not by Qt.
