### ISSUE TITLE
Anything can be done to improve the colors when using with P4Merge (Qt5)?

### ISSUE THREAD

**Issue by ransagy** [ColinDuquesnoy/QDarkStyleSheet#46]
I've tried using this style with P4Merge (https://www.perforce.com/product/components/perforce-visual-merge-and-diff-tools) by adding it under the P4VResources folder and named p4vstyle.qss (As they load such a style if it exists).

![capture](https://cloud.githubusercontent.com/assets/6785058/22392847/96bdba2c-e506-11e6-9cea-8dc3f5cf566a.PNG)

This works for most elements, but the diff line backgrounds are off. Any idea if anything can be added to the stylesheet to control that?

Thank in advance and sorry if this is way too specific/per-app to be relevant.

**Comment by ColinDuquesnoy** [comment]
I don't know. This really depends on how they made the diff line background. If they are using a custom widget and do their own rendering there are little chances you can change that with a stylesheet, unless they exposed some Q_PROPERTY (see http://doc.qt.io/qt-5/stylesheet-syntax.html#setting-qobject-properties). I'd suggest you ask them how you can customize the diff line.

**Comment by ransagy** [comment]
Figured as much. Thanks for the help and for this stylesheet in general :]
