### ISSUE TITLE
Stylesheet overriding custom background colors

### ISSUE THREAD

**Issue by Johndt6** [ColinDuquesnoy/QDarkStyleSheet#48]
I'm not sure if this is a fixable issue, but when I try to change the background color of a widget in PySide, this  stylesheet overwrites the change.

Take, for example, the following code, which displays three differently colored squares in a green-background widget:

```python

from PySide.QtCore import *
from PySide.QtGui import *

import qdarkstylesheet

class AllGreen(QWidget):
     def __init__(self):
         QWidget.__init__(self)
         layout = QVBoxLayout(self)

         self.w1 = QWidget(self)
         self.w1.setFixedSize(100, 100)
         self.w2 = QWidget(self)
         self.w2.setFixedSize(100, 100)
         self.w3 = QWidget(self)
         self.w3.setFixedSize(100, 100)

         palette = self.palette()
         role = self.backgroundRole()
         palette.setColor(role, QColor('green'))
         self.setPalette(palette)

         palette = self.w1.palette()
         role = self.w1.backgroundRole()
         palette.setColor(role, QColor('red'))
         self.w1.setPalette(palette)

         palette = self.w2.palette()
         role = self.w2.backgroundRole()
         palette.setColor(role, QColor('yellow'))
         self.w2.setPalette(palette)

         palette = self.w3.palette()
         role = self.w3.backgroundRole()
         palette.setColor(role, QColor('red'))
         self.w3.setPalette(palette)

         layout.addWidget(self.w1)
         layout.addWidget(self.w2)
         layout.addWidget(self.w3)

def testWidget():
     import sys
     a = QApplication(sys.argv)

     QObject.connect(a,SIGNAL("lastWindowClosed()"),a,SLOT("quit()"))

     w = AllGreen()
     w.w1.setAutoFillBackground(True)
     w.w2.setAutoFillBackground(True)
     w.w3.setAutoFillBackground(True)
     w.show()

     a.exec_()

if __name__ == "__main__":
     testWidget()
```

If we add the following line after creating the `QApplication`,

`a.setStyleSheet(qdarkstyle.load_stylesheet())`

Then the custom background colors are overwritten.

**Comment by GoelBiju** [comment]
Hello Mr. @Johndt6 ,

I am facing a similar issue when setting background images. The stylesheet's default background colour overrides any background image I want to set.

**Comment by ColinDuquesnoy** [comment]
@Johndt6 @GoelBiju QtStylsheet overrides QPalette, you have to extend the stylesheet for you particular widget type/instance, using e.g. an ID Selector. See http://doc.qt.io/qt-5.8/stylesheet-syntax.html#selector-types

**Comment by Johndt6** [comment]
@ColinDuquesnoy Great, thank you! I figured it might be something like that.

[Here's ](http://stackoverflow.com/questions/27159575/pyside-modifying-widget-colour-at-runtime-without-overwriting-stylesheet) a good explanation I've found on SO for overwriting the stylesheet.

**Comment by GoelBiju** [comment]
Thank you Mr. @ColinDuquesnoy  and Mr. @Johndt6  for the resources and help. I will try to see if I can get this issue solved.

**Comment by ColinDuquesnoy** [comment]
@GoelBiju Have you found a solution? Can I close this issue?

**Comment by GoelBiju** [comment]
Sorry Mr. Duquesnoy, I didn't find a solution where I could have both of them at the same time. You can close it anyhow, thank you for your help!
