### ISSUE TITLE
highlight misalignment issue

### ISSUE THREAD

**Issue by Phantom12** [ColinDuquesnoy/QDarkStyleSheet#57]
Hi ColinDuquesnoy, I recently found QDarkStyleSheet and gave it a try. Thank you for your fantastic work! However, I seem to have encounter a small bug. The problem is with a right click menu I created with QMenu. When the mouse hovers on one action, it will be highlighted with blue color, but the highlight seems to be positioned a bit too much on the right side instead of in the middle. Sorry I may not express myself very clearly. I think a screenshot will explain better. The first image below is the default Qt style, and the second is after applying QDarkStyleSheet. Could you please confirm the issue and help fix it?
![default](https://cloud.githubusercontent.com/assets/4783016/26779465/ccc81176-4a28-11e7-9a7c-e6009168edbb.png)
![qdarkstylesheet](https://cloud.githubusercontent.com/assets/4783016/26779531/120d4cf6-4a29-11e7-8467-a5f58144f123.png)

**Comment by ColinDuquesnoy** [comment]
I'll have a look, thanks for reporting

**Comment by Phantom12** [comment]
Hi ColinDuquesnoy, any luck in identifying the issue and possibly fixing it? Thanks

**Comment by Raincode** [comment]
Hi there,

a possible solution would be to remove `margin-left: 5px;` on line 238 unter `QMenu::item`. However, I am not sure if there are situations where you need this margin for visual reasons. In that case it may become slightly more complicated. I created a new Widgets Project and added a menu item to the menu bar to test.

It's quite late now, but I may be able to submit a pull request if wanted.

**Comment by ColinDuquesnoy** [comment]
Fix by PR #60
