### ISSUE TITLE
Cannot resize QWidget anymore

### ISSUE THREAD

**Issue by mainczjs** [ColinDuquesnoy/QDarkStyleSheet#58]
I use qdarkstylesheet to distinguish certain QMdiSubwindows from others in an QMDIArea setup. After applying the stylesheet, the widgets cannot be resized anymore. This happens with PyQt5.7 and Python 3.5 on Windows and Ubuntu 14.10

**Comment by ColinDuquesnoy** [comment]
AFAIK QMDIArea and QMDISubWindow do not support stylesheet (see _http://stackoverflow.com/questions/
4639407/how-to-customize-the-titlebar-of-a-qmdisubwindow-with-qss_)

I don't think there is anything I can do to help fixing your issue.
