### ISSUE TITLE
Selected Tab color for QTabWidget slightly misleading

### ISSUE THREAD

**Issue by Raincode** [ColinDuquesnoy/QDarkStyleSheet#59]
Take a look at the following picture and guess which Tab is selected in the 3 screenshots: http://i.imgur.com/CNWrggO.png

I found myself falling for the color scheme for the selected vs. unselected tabs. The darker background color is used for "selected", which I personally find to be slightly misleading, especially if you have 2 Tabs. I always feel like the lighter highlighted tab should be the one actually selected, as seen in the default windows theme and firefox.

As I already said, this is just my personal opinion and rather subjective, so let me know what you think. I'm sure I could get used to it.

**Comment by ColinDuquesnoy** [comment]
It's true to it can be confugsing. I don't have much time and intereset for the stylesheet for now (have been working a lot with QML the last months) so feel free to submit a PR with screenshots.

**Comment by dpizetta** [comment]
I'm working on this fix and including some more features, such as more complex examples. Take a look.

![screenshot linux 2018-02-02 17 26 25](https://user-images.githubusercontent.com/5084939/35751241-ee3e0a48-083e-11e8-83fb-4fb213032a9c.png)
![screenshot linux 2018-02-02 17 26 06](https://user-images.githubusercontent.com/5084939/35751246-f0bd39c4-083e-11e8-9876-18f95f7eafe1.png)

Soon I will create a new PR. Tks
