### ISSUE TITLE
QMessageBox buttons width is much smaller than required

### ISSUE THREAD

**Issue by nateshmbhat** [ColinDuquesnoy/QDarkStyleSheet#61]
![windowsnap](https://user-images.githubusercontent.com/23279926/29076287-b9d1aa7e-7c72-11e7-9990-39c8aead5659.PNG)

___

As shown in the above image , the size of Ok and cancel buttons are very small . can u please increase the width to the original width ?

**Comment by ColinDuquesnoy** [comment]
Every button has the same padding, not just the message box one and there is no such thing as original width (remember the stylesheet is cross platform).

Sorry I won't fix that but feel free to fork the project and adapt it to your taste.
