### ISSUE TITLE
Tooltip of QcomboBox not shown correctly

### ISSUE THREAD

**Issue by tdegeus** [ColinDuquesnoy/QDarkStyleSheet#62]
Great work on the theme, I absolutely love it!

I found a minor issue, where the tooltip of a QcomboBox is not shown correctly. Instead of the text an empty box is shown (see screenshot). The tooltips of the other widgets work fine. Also this issue is consistent for all QcomboBoxes in my application. (I'm on Qt 5.8)

<img width="261" alt="screen shot 2017-08-13 at 12 30 00" src="https://user-images.githubusercontent.com/7030445/29248883-8862b5a0-8023-11e7-9c67-b1d933a153e3.png">

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting.

My interest in the stylesheet is very low at the moment because I am moving from QtWidgets to QML. It may take some time before I get back to the stylesheet and fix the bug but if anyone find a solution I will merge a bug fix pull request.

**Comment by tdegeus** [comment]
Unfortunately I have little experience with the style definitions, but if you give me some directives I can give it a try.

**Comment by ColinDuquesnoy** [comment]
The qt documentation is a good start:

- http://doc.qt.io/qt-5.9/stylesheet.html
- http://doc.qt.io/qt-5/stylesheet-reference.html

The easiest way to work on the stylesheet is by using the python based examples (pyside, pyqt4 or pyqt5): https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/example. Feel free to modify the example.ui with qt designer (e.g. to add a tooltip to a combo box) and recompile ui using ``compile_ui.sh``.

To recompile the stylesheet for use in the python example, you need to run [compile_qrc script](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/compile_qrc.py)
