### ISSUE TITLE
problem with QspinBox

### ISSUE THREAD

**Issue by seghier** [ColinDuquesnoy/QDarkStyleSheet#64]
the spinbox look bad

**Comment by ColinDuquesnoy** [comment]
Hmm this is rather subjective and fall a bit short. Why do they look bad? What could be done to improve them?

 I personally think they look good.

**Comment by seghier** [comment]
thanks; it doesn't look like original spinbox ; the arrows are not together (see images)
https://i.imgbox.com/dIbZWila.jpg
https://i.imgbox.com/wEAjUqjS.jpg

**Comment by ColinDuquesnoy** [comment]
There is no such thing as the original because spinbox look different depending on the platform. The  look I choose to implement was based in the oxygen style from KDE (If I remember correctly).

Feel free to fork the stylesheet and adapt it to your taste.

**Comment by seghier** [comment]
thanks for information
i used windows 10 how i can change the stylesheet ?

**Comment by ColinDuquesnoy** [comment]
Edit [style.qss](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/style.qss), add it to your resource file (.qrc) and load it in your application.
