### ISSUE TITLE
QTreeView anc QListView unchecked image ist not correctly defined

### ISSUE THREAD

**Issue by aitormoreno** [ColinDuquesnoy/QDarkStyleSheet#66]
There is a bug in style.qss (line 986) introduced in commit 497522cca77206bb4f77ead1bf5cc88a4280be61
It should be:
`QTreeView::indicator:unchecked, QListView::indicator:unchecked`

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting. May I ask you to submit a PR please?

**Comment by ColinDuquesnoy** [comment]
Fix in #67
