### ISSUE TITLE
Images license

### ISSUE THREAD

**Issue by fkorsa** [ColinDuquesnoy/QDarkStyleSheet#68]
The embedded picture resources have no license attached. The MIT license cannot apply to them, because its terms are related to software resources only.

Could you indicate somewhere what is the license attached to these pictures?

**Comment by ColinDuquesnoy** [comment]
You're right. They should be licensed under the Creative Common license. I will add a note about that in the readme and license file.

**Comment by fkorsa** [comment]
Alright, thanks!

Great style sheet by the way.

**Comment by dpizetta** [comment]
I can change it. I recommend CC-BY. 
[Licenses](https://creativecommons.org/licenses/)

I was thinking of keeping the licenses information just in one file (COPYING -> LICENSE.md (MIT+CC)) and remove the terms from other files to keep easy to update dates.

Are you ok with it @ColinDuquesnoy ?

**Comment by ColinDuquesnoy** [comment]
@dpizetta Yes, I am ok with it. 👍  I think this exactly how I'd have done it.

**Comment by dpizetta** [comment]
Closed with [this](https://github.com/ColinDuquesnoy/QDarkStyleSheet/commit/306849df3e2fcdfcad3c631e553af5f791513723) commit.
