### ISSUE TITLE
Update travis file

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#74]
Broken after commit SHA 4006220679bc0e1e807b6c45c7c0b0237afdfba4.
Update example calls.

**Comment by ColinDuquesnoy** [comment]
Are you aware build still fails on travis?

**Comment by dpizetta** [comment]
Yep, I forgot to reopen.

I'm trying to solve this, one of the problems (import), my editor changed the place where its called, so before including into PATH. 

The other one, there is no system_packages for python dist that does not default in Linux. I'm trying to change to pip install, but it is not too simple for qt-things :(

I'll push a patch, for now, solving the first one and using default dist for the second.
