### ISSUE TITLE
It should exist so many colors in style palette?

### ISSUE THREAD

**Issue by dpizetta** [ColinDuquesnoy/QDarkStyleSheet#75]
Hi, I've changed some things and I see that (using CSS color extractor) that there are many colors in the stylesheet and some almost identical. Can we simplify this pallet? (Ex. #454545, #3A3939, #393838 for me is practically the same).

![screenshot linux 2018-02-07 14 39 44](https://user-images.githubusercontent.com/5084939/35929215-21c5e54a-0c16-11e8-9d37-5755cb734c6f.png)

My idea, in the future, is that we will have a short pallet, say 10 colors (including tones) that you can choose to automatically be changed. The main change, for example, would be in the color for selection actions, i.e, now the selection color marker is blue and I would like to use green, in other application. The short pallet makes this easy to change.

I'd like to implement some simple functions that allow this feature, showing the old and new pallet.

What do you think, @ColinDuquesnoy ?

**Comment by ColinDuquesnoy** [comment]
> Can we simplify this pallet?

I all for simplification, go!

> My idea, in the future, is that we will have a short pallet, say 10 colors (including tones) that you can choose to automatically be changed. The main change, for example, would be in the color for selection actions, i.e, now the selection color marker is blue and I would like to use green, in other application. The short pallet makes this easy to change.

That sounds good. Just make sure to not forget C++ users if you implement this (a header only solution where users can just copy the header to their application sounds reasonable).

**Comment by dpizetta** [comment]
Close with #79
