### ISSUE TITLE
Are you planning to support pyside2?

### ISSUE THREAD

**Issue by ok97465** [ColinDuquesnoy/QDarkStyleSheet#81]
Are you planning to support pyside2?

**Comment by ColinDuquesnoy** [comment]
@ok97465 Why did you close this issue?

I don't plan to add pyside2 support but @dpizetta might. @dpizetta Do you have such plans?

**Comment by dpizetta** [comment]
@ok97465, if this not requires a big reworking, yes, but is not my priority now. I think that it would be easy because PySide2 is based on Qt5. In addition, PySide2 is not stable yet. I'm working on those [projects](https://github.com/ColinDuquesnoy/QDarkStyleSheet/projects) now :) I tag this as a wishlist item.

**Comment by fredrikaverpil** [comment]
PySide2 is about to get stable. This is their [technical preview](http://blog.qt.io/blog/2018/06/13/qt-python-5-11-released/): http://download.qt.io/official_releases/QtForPython/pyside2/

**Comment by dpizetta** [comment]
Wow, it is nice to ear that! Unfortunately, they were not able to join to PyPI yet. I've been testing in version 3 - branch dev, and it is working. Soon I will push a stable version of QDarkStyle v.3 :)

**Comment by fredrikaverpil** [comment]
> Unfortunately, they were not able to join to PyPI yet

Yes, hopefully that will sort itself out. But you managed to install it, right? You can use pip or pipenv.

> I've been testing in version 3 - branch dev, and it is working.
> ...
> I'd like to ask you to try the version in branch dev if possible.

That's absolutely awesome news, I'll give it a spin.

**Comment by fredrikaverpil** [comment]
I just installed it and it seems to play nice with PySide2.

```
pipenv install git+https://github.com/ColinDuquesnoy/QDarkStyleSheet.git@dev#egg=QDarkStyleSheet
```

**Comment by dpizetta** [comment]
> But you managed to install it, right? You can use pip or pipenv.

I've been using dev version until now: 
- pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.9/latest/ pyside2 --trusted-host download.qt.io
- pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.11/latest/ pyside2 --trusted-host download.qt.io
Now I can check stable version too. :)

> I just installed it and it seems to play nice with PySide2.

This is music to my ears :) Soon it will be more nice changes, making qdarkstyle more graceful. 

Please, keep us up to date with your feelings about qdarkstyle 3. Tks again.
