### ISSUE TITLE
Remove dashed border for QSplitter::handle and QMainWindow::separator

### ISSUE THREAD

**Issue by thestr4ng3r** [ColinDuquesnoy/QDarkStyleSheet#86]
This is obviously a question of taste. However I think the dashed borders here look kind of ugly:
![bildschirmfoto vom 2018-03-08 13-15-49](https://user-images.githubusercontent.com/1460997/37151155-a983cd88-22d4-11e8-967a-f0ab5c0293be.png)
Especially with a lot of UI elements, it just makes everything look kind of cluttered.
I have just pushed a small change to our project which includes the theme: https://github.com/radareorg/cutter/commit/7b552694f039649c071b7b9749f29bc51df5f99b

If you disagree, just close this issue. Otherwise I can make a PR.

**Comment by dpizetta** [comment]
Hi, I agreed. I'm working on a new version with a lot of changes, including simplifying the palette, as mentioned in [projects](https://github.com/ColinDuquesnoy/QDarkStyleSheet/projects). This is a preview of it (but not the final aspect). I ask you to wait for the next version and/or use your change until that. After that, if you have another concern we can discuss later. Thank you for your option :)

I'm closing and marking this issue as invalid until the next version. 

![screenshot linux 2018-03-08 09 41 11](https://user-images.githubusercontent.com/5084939/37151832-e8dc8d54-22b5-11e8-855d-9b9f48e47fd6.png)

**Comment by thestr4ng3r** [comment]
Nice, thanks for the info!
