### ISSUE TITLE
TreeView Dropdown Arrow not Visible

### ISSUE THREAD

**Issue by CaptainKraft** [ColinDuquesnoy/QDarkStyleSheet#88]
The arrow next to an item with children is not visible. It's probably the same color as the background.

**Comment by dpizetta** [comment]
Hi, thanks for reporting this. I'll check and should be included in the next release.

**Comment by CaptainKraft** [comment]
It turns out, the missing arrow was because I didn't have the path to the image files set correctly. I'm no longer using QMake and Qt-related build tools, so setting the path to these images has been a pain.

I'm not sure how to write the qss so that it finds the correct relative path. Right now, I use an absolute path.

**Comment by dpizetta** [comment]
Ok, so I'll mark this as won't fix then close. If you have any other issues, please let us know
