### ISSUE TITLE
Why automatic loading from PySide?

### ISSUE THREAD

**Issue by flutefreak7** [ColinDuquesnoy/QDarkStyleSheet#89]
I was getting crashes in a pyinstaller deployed application because I was calling `load_stylesheet()` and didn't realize that `pyside=True` is the default.  Since PySide wasn't bundled in my application the import error would crash it.

If the qt_api isn't specified in the import could a pyside import error perhaps be caught?  I think this is how qt shims like anyqt or qt.py or pyqtgraph's qt_compat do it.  I thought that I could get it working by setting the environment variable, but now I realize that to check the environment variable requires a different call to `load_stylesheet_from_encironment()`.  I guess I'm just suggesting it could more gracefully handled the scenario where PySide isn't available because I'm intending it to use PyQt5.

I'm of course fine with just setting pyside=False now that I see where the error is coming from.

**Comment by dpizetta** [comment]
Hi, I agreed. I'm working on a new version that includes a new way to import Qt things. Instead of using 'import' I would like to use importlib from Python. 
Maybe the default situation is getting the available Qt binding if there is only one installed. Those changes are planned to be implemented in version 3. We can show a DeprecationWarning for that change of not assuming pyside=True. I will explicitly talk about it on the projects list. Tks

**Comment by ColinDuquesnoy** [comment]
@dpizetta  instead of reinventing the wheel, I'd suggest to use and to depends on an existing solution (e.g. [QtPy](https://github.com/spyder-ide/qtpy)  or any other one that you might know of). What do you think?

**Comment by dpizetta** [comment]
If you are ok with introducing a dependence, for me is even better. The idea of doing direct imports is to not depend on any other package, e.g. QtPy. If the idea of QtPy is ok, it is basically already implemented, we need simply remove the other ones. Depending on QtPy for me is not a problem. :)

**Comment by ColinDuquesnoy** [comment]
It's not a problem. I wrote QDarkStylesheet way before solutions like QtPy existed. If it simplifies our code then it's a good thing and we should use it.

**Comment by dpizetta** [comment]
Closing due 98d4632ca1570b8497d7452b5ceec53a0572f8b9, in new version 3.0.
