### ISSUE TITLE
It doesnt work in my Spyder IDE

### ISSUE THREAD

**Issue by p166whc** [ColinDuquesnoy/QDarkStyleSheet#90]
After Installation 
What should I do afterward?
Is it support the latest version of Spyder?

**Comment by dpizetta** [comment]
Hi, QDarkStyle is supposed to work with it, but as mentioned [**here**](https://github.com/spyder-ide/spyder/issues/2350), there are some widgets that are specialized, in the future should work with changes in Spyder. In the link, there are some other options. I would like to use QDarkStyle too, but some widgets and icons (from Spyder) are note prepared, see my test below.
![screenshot linux 2018-04-02 12 50 00](https://user-images.githubusercontent.com/5084939/38203236-f024c856-3674-11e8-9f4b-5a14f82b90cb.png)
