### ISSUE TITLE
Missing style of QStandardItem built-in checkbox

### ISSUE THREAD

**Issue by KcHNST** [ColinDuquesnoy/QDarkStyleSheet#92]
### Describe Your Environment

[Versions from your environment]

- QDarkStyle: 2.5.3
- OS: Win 7
- Python: 3.6.5
- PyQt: 5.10.1

### Language

Python

### Description / Steps to Reproduce

The built-in checkbox of QStandardItem does not used the styled checkbox whenever the check state is Qt::PartiallyChecked.

### Actual Result

The problem checkbox shown among correctly styled checkboxes:

![qstandarditemcheckbox](https://user-images.githubusercontent.com/32450453/39135020-4d22a880-4718-11e8-9ddd-892cccb596da.png)

### Expected Results / Proposed Result

The style should look like that of QCheckBox presumably?

![qcheckbox](https://user-images.githubusercontent.com/32450453/39134930-1914cae6-4718-11e8-8f5e-20966e6bc1d5.png)

**Comment by ColinDuquesnoy** [comment]
Unfortunately, not everything can be customized using a stylesheet. You need to implement a custom delegate to customize items in a view: http://doc.qt.io/qt-4.8/qabstractitemdelegate.

@dpizetta Unless you know a workaround, I'd close this issue as won't fix (as in #52 ).

**Comment by KcHNST** [comment]
Closed due to not being customized using a stylesheet.

**Comment by ColinDuquesnoy** [comment]
Reopening because I forget @aitormoreno actually found a solution in #67. I think he just forget the Indeterminate state. We should fix it.

**Comment by dpizetta** [comment]
I will check this as soon as possible, thanks

**Comment by KcHNST** [comment]
Something like this?

Idle:
```
QTreeView::indicator:indeterminate,
QListView::indicator:indeterminate {
    image: url(:/qss_icons/rc/checkbox_indeterminate.png);
}
```
Focus:
```
QTreeView::indicator:indeterminate:hover,
QTreeView::indicator:indeterminate:focus,
QTreeView::indicator:indeterminate:pressed,
QListView::indicator:indeterminate:hover,
QListView::indicator:indeterminate:focus,
QListView::indicator:indeterminate:pressed {
    image: url(:/qss_icons/rc/checkbox_indeterminate_focus.png);
}
```

**Comment by dpizetta** [comment]
Hi @KcHNST , could you add a PR for this? I think it is correct. Try to check if it works in your app. Tks again!
