### ISSUE TITLE
QGroupBox has not image for check/unchek state.

### ISSUE THREAD

**Issue by sawt00th** [ColinDuquesnoy/QDarkStyleSheet#93]
### Environment

- QDarkStyle: 2.5.3
- OS: Windows 10/ 7
- Qt version: Qt 5.10
- Language: C++

### Description 

QGroupBox widget not has indicator style, when he usage as "checkable".
Actual Result:
![groupbox_bug](https://user-images.githubusercontent.com/14891592/39321990-2d2da90a-4991-11e8-9b86-86fb1145761d.png)
I'w get pull request for fix that problem

**Comment by dpizetta** [comment]
Closed by #94
